# 2. Model Training & Hyperparameter Tuning
Models compared:
- **Logistic Regression** — interpretable baseline, no tuning
- **XGBoost** — tuned with Optuna (100 trials), `scale_pos_weight` tuned as a hyperparameter, optimized for PR-AUC
- **Random Forest** — `class_weight='balanced_subsample'`, tuned with Optuna (100 trials)
- **LightGBM** — `is_unbalance=True` + tuned `scale_pos_weight`, tuned with Optuna (100 trials)

Primary metric: **PR-AUC** (average precision) — more sensitive to minority-class performance than ROC-AUC under ~9% positive-class imbalance.
Precision/Recall/F1 for each model are reported at that model's own F1-optimal threshold (not the default 0.5), since raw probabilities cluster well below 0.5 for all models here.

> Temporal split: train 2015-2022, test 2023-2025 (no data leakage).

In [1]:
import joblib
import numpy as np
import pandas as pd
import warnings
import optuna
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import (
    roc_auc_score, average_precision_score, precision_recall_curve,
    classification_report, recall_score, precision_score, f1_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import mlflow
import mlflow.sklearn

warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)

mlflow.set_tracking_uri('sqlite:///mlflow.db')
mlflow.set_experiment('njit_dropout_prediction')

OUTPUT_DIR   = Path('outputs')
RANDOM_STATE = 42
CV_FOLDS     = 5
N_TRIALS     = 100

X_train = joblib.load(OUTPUT_DIR / 'X_train.pkl')
X_test  = joblib.load(OUTPUT_DIR / 'X_test.pkl')
y_train = joblib.load(OUTPUT_DIR / 'y_train.pkl')
y_test  = joblib.load(OUTPUT_DIR / 'y_test.pkl')

print(f"Train: {X_train.shape} | Test: {X_test.shape}")
print(f"Train positive rate: {y_train.mean():.4f} | Test: {y_test.mean():.4f}")

C:\Users\prati\Desktop\Project\ARR_NJIT_RD2\ARR_NJIT_RD2\ML_Model\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2026/07/02 08:33:36 INFO mlflow.store.db.utils: Creating initial MLflow database tables...

2026/07/02 08:33:36 INFO mlflow.store.db.utils: Updating database tables

2026/07/02 08:33:37 INFO mlflow.tracking.fluent: Experiment with name 'njit_dropout_prediction' does not exist. Creating a new experiment.

Train: (124463, 30) | Test: (65156, 30)
Train positive rate: 0.1072 | Test: 0.1065

## 2.1 Shared evaluation helper
Computes PR-AUC (threshold-independent) plus Precision/Recall/F1 at the model's own F1-optimal threshold.

In [2]:
def evaluate_model(name, model, X_test, y_test, cv_metric_value, cv_metric_std='-', stage='baseline'):
    y_prob = model.predict_proba(X_test)[:, 1]
    test_auc  = roc_auc_score(y_test, y_prob)
    pr_auc    = average_precision_score(y_test, y_prob)

    prec, rec, thresholds = precision_recall_curve(y_test, y_prob)
    f1_scores = 2 * prec * rec / (prec + rec + 1e-8)
    best_idx  = f1_scores[:-1].argmax()  # last point has no threshold
    opt_threshold = thresholds[best_idx]

    y_pred_opt = (y_prob >= opt_threshold).astype(int)
    precision  = precision_score(y_test, y_pred_opt, zero_division=0)
    recall     = recall_score(y_test, y_pred_opt, zero_division=0)
    f1         = f1_score(y_test, y_pred_opt, zero_division=0)

    print(f"{name}: CV={cv_metric_value:.4f} | Test AUC={test_auc:.4f} | PR-AUC={pr_auc:.4f} | "
          f"opt_thr={opt_threshold:.4f} | Precision={precision:.4f} | Recall={recall:.4f} | F1={f1:.4f}")

    # Log this model to MLflow: params, metrics, and the fitted model artifact
    with mlflow.start_run(run_name=name):
        raw_params = model.get_params()
        loggable_params = {k: v for k, v in raw_params.items() if isinstance(v, (str, int, float, bool)) or v is None}
        mlflow.log_params(loggable_params)
        mlflow.set_tags({"stage": stage, "algorithm": name})
        mlflow.log_metrics({
            "cv_pr_auc": float(cv_metric_value),
            "test_auc": float(test_auc),
            "pr_auc": float(pr_auc),
            "optimal_threshold": float(opt_threshold),
            "precision_at_risk": float(precision),
            "recall_at_risk": float(recall),
            "f1_at_risk": float(f1),
        })
        mlflow.sklearn.log_model(model, name="model", serialization_format="cloudpickle")

    return {
        "Model": name,
        "CV PR-AUC": round(cv_metric_value, 4),
        "CV Std": cv_metric_std if cv_metric_std == '-' else round(cv_metric_std, 4),
        "Test AUC": round(test_auc, 4),
        "PR-AUC": round(pr_auc, 4),
        "Optimal Threshold": round(float(opt_threshold), 4),
        "Precision (at-risk)": round(precision, 4),
        "Recall (at-risk)": round(recall, 4),
        "F1 (at-risk)": round(f1, 4),
    }

## 2.2 Baseline Models (default hyperparameters + class balancing)

In [3]:
cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
pos_weight = (1 - y_train.mean()) / y_train.mean()

baseline_models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            class_weight="balanced", max_iter=2000,
            solver="saga", random_state=RANDOM_STATE,
        )),
    ]),
    "XGBoost (baseline)": XGBClassifier(
        n_estimators=200, max_depth=6, learning_rate=0.1,
        scale_pos_weight=pos_weight, eval_metric="aucpr",
        random_state=RANDOM_STATE, verbosity=0,
    ),
    "Random Forest (baseline)": RandomForestClassifier(
        n_estimators=300, max_depth=None, class_weight="balanced_subsample",
        random_state=RANDOM_STATE, n_jobs=-1,
    ),
    "LightGBM (baseline)": LGBMClassifier(
        n_estimators=200, max_depth=6, learning_rate=0.1,
        is_unbalance=True, random_state=RANDOM_STATE, verbosity=-1,
    ),
}

results = []
fitted_models = {}

for name, model in baseline_models.items():
    cv_scores = cross_val_score(
        model, X_train, y_train, cv=cv, scoring="average_precision", n_jobs=-1
    )
    model.fit(X_train, y_train)
    results.append(evaluate_model(name, model, X_test, y_test, cv_scores.mean(), cv_scores.std(), stage="baseline"))
    fitted_models[name] = model

pd.DataFrame(results)

Logistic Regression: CV=0.1274 | Test AUC=0.5729 | PR-AUC=0.1271 | opt_thr=0.4886 | Precision=0.1269 | Recall=0.7838 | F1=0.2184

2026/07/02 08:37:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

2026/07/02 08:37:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

XGBoost (baseline): CV=0.1305 | Test AUC=0.6001 | PR-AUC=0.1349 | opt_thr=0.4682 | Precision=0.1342 | Recall=0.7275 | F1=0.2266

2026/07/02 08:38:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Random Forest (baseline): CV=0.1188 | Test AUC=0.5693 | PR-AUC=0.1252 | opt_thr=0.0663 | Precision=0.1221 | Recall=0.7849 | F1=0.2113

2026/07/02 08:38:35 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LightGBM (baseline): CV=0.1305 | Test AUC=0.6010 | PR-AUC=0.1359 | opt_thr=0.4508 | Precision=0.1336 | Recall=0.7696 | F1=0.2277

,Model,CV PR-AUC,CV Std,Test AUC,PR-AUC,Optimal Threshold,Precision (at-risk),Recall (at-risk),F1 (at-risk)
0,Logistic Regression,0.1274,0.0022,0.5729,0.1271,0.4886,0.1269,0.7838,0.2184
1,XGBoost (baseline),0.1305,0.0015,0.6001,0.1349,0.4682,0.1342,0.7275,0.2266
2,Random Forest (baseline),0.1188,0.0010,0.5693,0.1252,0.0663,0.1221,0.7849,0.2113
3,LightGBM (baseline),0.1305,0.0018,0.6010,0.1359,0.4508,0.1336,0.7696,0.2277

## 2.3 Hyperparameter Tuning with Optuna
Logistic Regression is kept as an interpretable baseline with no tuning. XGBoost, Random Forest, and LightGBM are each tuned with 100 Bayesian trials, optimizing **PR-AUC** (`average_precision`) via 3-fold CV. `scale_pos_weight` is tuned as a hyperparameter (not fixed) for the gradient-boosted models.

### 2.3.1 XGBoost

In [4]:
def objective_xgb(trial):
    params = {
        "n_estimators":     trial.suggest_int("n_estimators", 100, 600),
        "max_depth":        trial.suggest_int("max_depth", 3, 10),
        "learning_rate":    trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample":        trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma":            trial.suggest_float("gamma", 0.0, 5.0),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 5.0, 20.0),
        "eval_metric":      "aucpr",
        "random_state":     RANDOM_STATE,
        "verbosity":        0,
    }
    model = XGBClassifier(**params)
    scores = cross_val_score(
        model, X_train, y_train,
        cv=StratifiedKFold(3, shuffle=True, random_state=RANDOM_STATE),
        scoring="average_precision", n_jobs=-1,
    )
    return scores.mean()

print("Tuning XGBoost with Optuna (100 trials, optimizing PR-AUC) ...")
study_xgb = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study_xgb.optimize(objective_xgb, n_trials=N_TRIALS, show_progress_bar=True)
print(f"Best CV PR-AUC: {study_xgb.best_value:.4f}")
print(f"Best params: {study_xgb.best_params}")

Tuning XGBoost with Optuna (100 trials, optimizing PR-AUC) ...

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.119659:   0%|          | 0/100 [00:06<?, ?it/s]

Best trial: 0. Best value: 0.119659:   1%|          | 1/100 [00:06<10:45,  6.52s/it]

Best trial: 1. Best value: 0.133569:   1%|          | 1/100 [00:13<10:45,  6.52s/it]

Best trial: 1. Best value: 0.133569:   2%|▏         | 2/100 [00:13<10:44,  6.57s/it]

Best trial: 1. Best value: 0.133569:   2%|▏         | 2/100 [00:17<10:44,  6.57s/it]

Best trial: 1. Best value: 0.133569:   3%|▎         | 3/100 [00:17<08:52,  5.49s/it]

Best trial: 1. Best value: 0.133569:   3%|▎         | 3/100 [00:23<08:52,  5.49s/it]

Best trial: 1. Best value: 0.133569:   4%|▍         | 4/100 [00:23<09:18,  5.82s/it]

Best trial: 1. Best value: 0.133569:   4%|▍         | 4/100 [00:25<09:18,  5.82s/it]

Best trial: 1. Best value: 0.133569:   5%|▌         | 5/100 [00:25<07:05,  4.48s/it]

Best trial: 5. Best value: 0.137138:   5%|▌         | 5/100 [00:28<07:05,  4.48s/it]

Best trial: 5. Best value: 0.137138:   6%|▌         | 6/100 [00:28<06:00,  3.84s/it]

Best trial: 5. Best value: 0.137138:   6%|▌         | 6/100 [00:32<06:00,  3.84s/it]

Best trial: 5. Best value: 0.137138:   7%|▋         | 7/100 [00:32<06:16,  4.04s/it]

Best trial: 5. Best value: 0.137138:   7%|▋         | 7/100 [00:34<06:16,  4.04s/it]

Best trial: 5. Best value: 0.137138:   8%|▊         | 8/100 [00:34<05:16,  3.44s/it]

Best trial: 5. Best value: 0.137138:   8%|▊         | 8/100 [00:38<05:16,  3.44s/it]

Best trial: 5. Best value: 0.137138:   9%|▉         | 9/100 [00:38<05:25,  3.58s/it]

Best trial: 5. Best value: 0.137138:   9%|▉         | 9/100 [00:41<05:25,  3.58s/it]

Best trial: 5. Best value: 0.137138:  10%|█         | 10/100 [00:41<04:42,  3.14s/it]

Best trial: 5. Best value: 0.137138:  10%|█         | 10/100 [00:47<04:42,  3.14s/it]

Best trial: 5. Best value: 0.137138:  11%|█         | 11/100 [00:47<06:24,  4.32s/it]

Best trial: 5. Best value: 0.137138:  11%|█         | 11/100 [00:51<06:24,  4.32s/it]

Best trial: 5. Best value: 0.137138:  12%|█▏        | 12/100 [00:51<05:51,  4.00s/it]

Best trial: 5. Best value: 0.137138:  12%|█▏        | 12/100 [00:54<05:51,  4.00s/it]

Best trial: 5. Best value: 0.137138:  13%|█▎        | 13/100 [00:54<05:24,  3.73s/it]

Best trial: 5. Best value: 0.137138:  13%|█▎        | 13/100 [00:56<05:24,  3.73s/it]

Best trial: 5. Best value: 0.137138:  14%|█▍        | 14/100 [00:56<04:48,  3.36s/it]

Best trial: 5. Best value: 0.137138:  14%|█▍        | 14/100 [01:03<04:48,  3.36s/it]

Best trial: 5. Best value: 0.137138:  15%|█▌        | 15/100 [01:03<06:12,  4.38s/it]

Best trial: 5. Best value: 0.137138:  15%|█▌        | 15/100 [01:06<06:12,  4.38s/it]

Best trial: 5. Best value: 0.137138:  16%|█▌        | 16/100 [01:06<05:41,  4.06s/it]

Best trial: 5. Best value: 0.137138:  16%|█▌        | 16/100 [01:10<05:41,  4.06s/it]

Best trial: 5. Best value: 0.137138:  17%|█▋        | 17/100 [01:10<05:36,  4.05s/it]

Best trial: 5. Best value: 0.137138:  17%|█▋        | 17/100 [01:17<05:36,  4.05s/it]

Best trial: 5. Best value: 0.137138:  18%|█▊        | 18/100 [01:17<06:42,  4.91s/it]

Best trial: 5. Best value: 0.137138:  18%|█▊        | 18/100 [01:21<06:42,  4.91s/it]

Best trial: 5. Best value: 0.137138:  19%|█▉        | 19/100 [01:21<06:02,  4.47s/it]

Best trial: 5. Best value: 0.137138:  19%|█▉        | 19/100 [01:26<06:02,  4.47s/it]

Best trial: 5. Best value: 0.137138:  20%|██        | 20/100 [01:26<06:18,  4.73s/it]

Best trial: 5. Best value: 0.137138:  20%|██        | 20/100 [01:29<06:18,  4.73s/it]

Best trial: 5. Best value: 0.137138:  21%|██        | 21/100 [01:29<05:34,  4.24s/it]

Best trial: 5. Best value: 0.137138:  21%|██        | 21/100 [01:32<05:34,  4.24s/it]

Best trial: 5. Best value: 0.137138:  22%|██▏       | 22/100 [01:32<05:03,  3.89s/it]

Best trial: 5. Best value: 0.137138:  22%|██▏       | 22/100 [01:36<05:03,  3.89s/it]

Best trial: 5. Best value: 0.137138:  23%|██▎       | 23/100 [01:36<04:59,  3.89s/it]

Best trial: 5. Best value: 0.137138:  23%|██▎       | 23/100 [01:39<04:59,  3.89s/it]

Best trial: 5. Best value: 0.137138:  24%|██▍       | 24/100 [01:39<04:40,  3.69s/it]

Best trial: 5. Best value: 0.137138:  24%|██▍       | 24/100 [01:41<04:40,  3.69s/it]

Best trial: 5. Best value: 0.137138:  25%|██▌       | 25/100 [01:41<03:51,  3.09s/it]

Best trial: 5. Best value: 0.137138:  25%|██▌       | 25/100 [01:44<03:51,  3.09s/it]

Best trial: 5. Best value: 0.137138:  26%|██▌       | 26/100 [01:44<03:43,  3.02s/it]

Best trial: 5. Best value: 0.137138:  26%|██▌       | 26/100 [01:48<03:43,  3.02s/it]

Best trial: 5. Best value: 0.137138:  27%|██▋       | 27/100 [01:48<03:55,  3.22s/it]

Best trial: 5. Best value: 0.137138:  27%|██▋       | 27/100 [01:52<03:55,  3.22s/it]

Best trial: 5. Best value: 0.137138:  28%|██▊       | 28/100 [01:52<04:21,  3.63s/it]

Best trial: 5. Best value: 0.137138:  28%|██▊       | 28/100 [01:56<04:21,  3.63s/it]

Best trial: 5. Best value: 0.137138:  29%|██▉       | 29/100 [01:56<04:30,  3.81s/it]

Best trial: 5. Best value: 0.137138:  29%|██▉       | 29/100 [02:03<04:30,  3.81s/it]

Best trial: 5. Best value: 0.137138:  30%|███       | 30/100 [02:03<05:21,  4.59s/it]

Best trial: 5. Best value: 0.137138:  30%|███       | 30/100 [02:07<05:21,  4.59s/it]

Best trial: 5. Best value: 0.137138:  31%|███       | 31/100 [02:07<05:02,  4.39s/it]

Best trial: 5. Best value: 0.137138:  31%|███       | 31/100 [02:11<05:02,  4.39s/it]

Best trial: 5. Best value: 0.137138:  32%|███▏      | 32/100 [02:11<04:49,  4.25s/it]

Best trial: 5. Best value: 0.137138:  32%|███▏      | 32/100 [02:15<04:49,  4.25s/it]

Best trial: 5. Best value: 0.137138:  33%|███▎      | 33/100 [02:15<04:44,  4.25s/it]

Best trial: 5. Best value: 0.137138:  33%|███▎      | 33/100 [02:20<04:44,  4.25s/it]

Best trial: 5. Best value: 0.137138:  34%|███▍      | 34/100 [02:20<04:45,  4.32s/it]

Best trial: 5. Best value: 0.137138:  34%|███▍      | 34/100 [02:24<04:45,  4.32s/it]

Best trial: 5. Best value: 0.137138:  35%|███▌      | 35/100 [02:24<04:34,  4.23s/it]

Best trial: 5. Best value: 0.137138:  35%|███▌      | 35/100 [02:28<04:34,  4.23s/it]

Best trial: 5. Best value: 0.137138:  36%|███▌      | 36/100 [02:28<04:32,  4.26s/it]

Best trial: 5. Best value: 0.137138:  36%|███▌      | 36/100 [02:32<04:32,  4.26s/it]

Best trial: 5. Best value: 0.137138:  37%|███▋      | 37/100 [02:32<04:25,  4.22s/it]

Best trial: 5. Best value: 0.137138:  37%|███▋      | 37/100 [02:40<04:25,  4.22s/it]

Best trial: 5. Best value: 0.137138:  38%|███▊      | 38/100 [02:40<05:27,  5.29s/it]

Best trial: 5. Best value: 0.137138:  38%|███▊      | 38/100 [02:44<05:27,  5.29s/it]

Best trial: 5. Best value: 0.137138:  39%|███▉      | 39/100 [02:44<05:02,  4.96s/it]

Best trial: 5. Best value: 0.137138:  39%|███▉      | 39/100 [02:46<05:02,  4.96s/it]

Best trial: 5. Best value: 0.137138:  40%|████      | 40/100 [02:46<04:01,  4.03s/it]

Best trial: 5. Best value: 0.137138:  40%|████      | 40/100 [02:49<04:01,  4.03s/it]

Best trial: 5. Best value: 0.137138:  41%|████      | 41/100 [02:49<03:49,  3.89s/it]

Best trial: 5. Best value: 0.137138:  41%|████      | 41/100 [02:53<03:49,  3.89s/it]

Best trial: 5. Best value: 0.137138:  42%|████▏     | 42/100 [02:53<03:39,  3.79s/it]

Best trial: 5. Best value: 0.137138:  42%|████▏     | 42/100 [02:56<03:39,  3.79s/it]

Best trial: 5. Best value: 0.137138:  43%|████▎     | 43/100 [02:56<03:29,  3.68s/it]

Best trial: 5. Best value: 0.137138:  43%|████▎     | 43/100 [02:59<03:29,  3.68s/it]

Best trial: 5. Best value: 0.137138:  44%|████▍     | 44/100 [02:59<03:07,  3.34s/it]

Best trial: 5. Best value: 0.137138:  44%|████▍     | 44/100 [03:01<03:07,  3.34s/it]

Best trial: 5. Best value: 0.137138:  45%|████▌     | 45/100 [03:01<02:49,  3.09s/it]

Best trial: 5. Best value: 0.137138:  45%|████▌     | 45/100 [03:04<02:49,  3.09s/it]

Best trial: 5. Best value: 0.137138:  46%|████▌     | 46/100 [03:04<02:39,  2.96s/it]

Best trial: 5. Best value: 0.137138:  46%|████▌     | 46/100 [03:06<02:39,  2.96s/it]

Best trial: 5. Best value: 0.137138:  47%|████▋     | 47/100 [03:06<02:25,  2.74s/it]

Best trial: 5. Best value: 0.137138:  47%|████▋     | 47/100 [03:09<02:25,  2.74s/it]

Best trial: 5. Best value: 0.137138:  48%|████▊     | 48/100 [03:09<02:17,  2.64s/it]

Best trial: 5. Best value: 0.137138:  48%|████▊     | 48/100 [03:12<02:17,  2.64s/it]

Best trial: 5. Best value: 0.137138:  49%|████▉     | 49/100 [03:12<02:19,  2.73s/it]

Best trial: 5. Best value: 0.137138:  49%|████▉     | 49/100 [03:15<02:19,  2.73s/it]

Best trial: 5. Best value: 0.137138:  50%|█████     | 50/100 [03:15<02:22,  2.84s/it]

Best trial: 5. Best value: 0.137138:  50%|█████     | 50/100 [03:18<02:22,  2.84s/it]

Best trial: 5. Best value: 0.137138:  51%|█████     | 51/100 [03:18<02:29,  3.06s/it]

Best trial: 5. Best value: 0.137138:  51%|█████     | 51/100 [03:23<02:29,  3.06s/it]

Best trial: 5. Best value: 0.137138:  52%|█████▏    | 52/100 [03:23<02:44,  3.42s/it]

Best trial: 5. Best value: 0.137138:  52%|█████▏    | 52/100 [03:26<02:44,  3.42s/it]

Best trial: 5. Best value: 0.137138:  53%|█████▎    | 53/100 [03:26<02:35,  3.30s/it]

Best trial: 5. Best value: 0.137138:  53%|█████▎    | 53/100 [03:29<02:35,  3.30s/it]

Best trial: 5. Best value: 0.137138:  54%|█████▍    | 54/100 [03:29<02:31,  3.29s/it]

Best trial: 5. Best value: 0.137138:  54%|█████▍    | 54/100 [03:32<02:31,  3.29s/it]

Best trial: 5. Best value: 0.137138:  55%|█████▌    | 55/100 [03:32<02:25,  3.23s/it]

Best trial: 5. Best value: 0.137138:  55%|█████▌    | 55/100 [03:35<02:25,  3.23s/it]

Best trial: 5. Best value: 0.137138:  56%|█████▌    | 56/100 [03:35<02:13,  3.03s/it]

Best trial: 5. Best value: 0.137138:  56%|█████▌    | 56/100 [03:37<02:13,  3.03s/it]

Best trial: 5. Best value: 0.137138:  57%|█████▋    | 57/100 [03:37<02:08,  2.98s/it]

Best trial: 5. Best value: 0.137138:  57%|█████▋    | 57/100 [03:40<02:08,  2.98s/it]

Best trial: 5. Best value: 0.137138:  58%|█████▊    | 58/100 [03:40<02:05,  2.99s/it]

Best trial: 58. Best value: 0.13725:  58%|█████▊    | 58/100 [03:42<02:05,  2.99s/it]

Best trial: 58. Best value: 0.13725:  59%|█████▉    | 59/100 [03:42<01:49,  2.67s/it]

Best trial: 58. Best value: 0.13725:  59%|█████▉    | 59/100 [03:44<01:49,  2.67s/it]

Best trial: 58. Best value: 0.13725:  60%|██████    | 60/100 [03:44<01:37,  2.43s/it]

Best trial: 58. Best value: 0.13725:  60%|██████    | 60/100 [03:46<01:37,  2.43s/it]

Best trial: 58. Best value: 0.13725:  61%|██████    | 61/100 [03:46<01:29,  2.29s/it]

Best trial: 58. Best value: 0.13725:  61%|██████    | 61/100 [03:48<01:29,  2.29s/it]

Best trial: 58. Best value: 0.13725:  62%|██████▏   | 62/100 [03:48<01:20,  2.11s/it]

Best trial: 58. Best value: 0.13725:  62%|██████▏   | 62/100 [03:50<01:20,  2.11s/it]

Best trial: 58. Best value: 0.13725:  63%|██████▎   | 63/100 [03:50<01:15,  2.05s/it]

Best trial: 58. Best value: 0.13725:  63%|██████▎   | 63/100 [03:52<01:15,  2.05s/it]

Best trial: 58. Best value: 0.13725:  64%|██████▍   | 64/100 [03:52<01:11,  1.99s/it]

Best trial: 58. Best value: 0.13725:  64%|██████▍   | 64/100 [03:54<01:11,  1.99s/it]

Best trial: 58. Best value: 0.13725:  65%|██████▌   | 65/100 [03:54<01:11,  2.04s/it]

Best trial: 58. Best value: 0.13725:  65%|██████▌   | 65/100 [03:56<01:11,  2.04s/it]

Best trial: 58. Best value: 0.13725:  66%|██████▌   | 66/100 [03:56<01:13,  2.17s/it]

Best trial: 58. Best value: 0.13725:  66%|██████▌   | 66/100 [03:58<01:13,  2.17s/it]

Best trial: 58. Best value: 0.13725:  67%|██████▋   | 67/100 [03:58<01:08,  2.06s/it]

Best trial: 58. Best value: 0.13725:  67%|██████▋   | 67/100 [04:00<01:08,  2.06s/it]

Best trial: 58. Best value: 0.13725:  68%|██████▊   | 68/100 [04:00<01:01,  1.94s/it]

Best trial: 58. Best value: 0.13725:  68%|██████▊   | 68/100 [04:02<01:01,  1.94s/it]

Best trial: 58. Best value: 0.13725:  69%|██████▉   | 69/100 [04:02<01:02,  2.02s/it]

Best trial: 58. Best value: 0.13725:  69%|██████▉   | 69/100 [04:08<01:02,  2.02s/it]

Best trial: 58. Best value: 0.13725:  70%|███████   | 70/100 [04:08<01:35,  3.18s/it]

Best trial: 58. Best value: 0.13725:  70%|███████   | 70/100 [04:10<01:35,  3.18s/it]

Best trial: 58. Best value: 0.13725:  71%|███████   | 71/100 [04:10<01:24,  2.91s/it]

Best trial: 58. Best value: 0.13725:  71%|███████   | 71/100 [04:13<01:24,  2.91s/it]

Best trial: 58. Best value: 0.13725:  72%|███████▏  | 72/100 [04:13<01:23,  2.98s/it]

Best trial: 58. Best value: 0.13725:  72%|███████▏  | 72/100 [04:16<01:23,  2.98s/it]

Best trial: 58. Best value: 0.13725:  73%|███████▎  | 73/100 [04:16<01:19,  2.93s/it]

Best trial: 58. Best value: 0.13725:  73%|███████▎  | 73/100 [04:19<01:19,  2.93s/it]

Best trial: 58. Best value: 0.13725:  74%|███████▍  | 74/100 [04:19<01:12,  2.80s/it]

Best trial: 58. Best value: 0.13725:  74%|███████▍  | 74/100 [04:20<01:12,  2.80s/it]

Best trial: 58. Best value: 0.13725:  75%|███████▌  | 75/100 [04:20<01:01,  2.48s/it]

Best trial: 58. Best value: 0.13725:  75%|███████▌  | 75/100 [04:22<01:01,  2.48s/it]

Best trial: 58. Best value: 0.13725:  76%|███████▌  | 76/100 [04:22<00:54,  2.26s/it]

Best trial: 58. Best value: 0.13725:  76%|███████▌  | 76/100 [04:25<00:54,  2.26s/it]

Best trial: 58. Best value: 0.13725:  77%|███████▋  | 77/100 [04:25<00:55,  2.40s/it]

Best trial: 58. Best value: 0.13725:  77%|███████▋  | 77/100 [04:27<00:55,  2.40s/it]

Best trial: 58. Best value: 0.13725:  78%|███████▊  | 78/100 [04:27<00:50,  2.28s/it]

Best trial: 58. Best value: 0.13725:  78%|███████▊  | 78/100 [04:29<00:50,  2.28s/it]

Best trial: 58. Best value: 0.13725:  79%|███████▉  | 79/100 [04:29<00:47,  2.25s/it]

Best trial: 79. Best value: 0.137336:  79%|███████▉  | 79/100 [04:32<00:47,  2.25s/it]

Best trial: 79. Best value: 0.137336:  80%|████████  | 80/100 [04:32<00:47,  2.35s/it]

Best trial: 79. Best value: 0.137336:  80%|████████  | 80/100 [04:34<00:47,  2.35s/it]

Best trial: 79. Best value: 0.137336:  81%|████████  | 81/100 [04:34<00:43,  2.31s/it]

Best trial: 79. Best value: 0.137336:  81%|████████  | 81/100 [04:36<00:43,  2.31s/it]

Best trial: 79. Best value: 0.137336:  82%|████████▏ | 82/100 [04:36<00:39,  2.21s/it]

Best trial: 79. Best value: 0.137336:  82%|████████▏ | 82/100 [04:38<00:39,  2.21s/it]

Best trial: 79. Best value: 0.137336:  83%|████████▎ | 83/100 [04:38<00:36,  2.17s/it]

Best trial: 79. Best value: 0.137336:  83%|████████▎ | 83/100 [04:40<00:36,  2.17s/it]

Best trial: 79. Best value: 0.137336:  84%|████████▍ | 84/100 [04:40<00:33,  2.06s/it]

Best trial: 84. Best value: 0.137474:  84%|████████▍ | 84/100 [04:41<00:33,  2.06s/it]

Best trial: 84. Best value: 0.137474:  85%|████████▌ | 85/100 [04:41<00:29,  1.99s/it]

Best trial: 84. Best value: 0.137474:  85%|████████▌ | 85/100 [04:43<00:29,  1.99s/it]

Best trial: 84. Best value: 0.137474:  86%|████████▌ | 86/100 [04:43<00:27,  1.96s/it]

Best trial: 84. Best value: 0.137474:  86%|████████▌ | 86/100 [04:45<00:27,  1.96s/it]

Best trial: 84. Best value: 0.137474:  87%|████████▋ | 87/100 [04:45<00:25,  1.97s/it]

Best trial: 84. Best value: 0.137474:  87%|████████▋ | 87/100 [04:48<00:25,  1.97s/it]

Best trial: 84. Best value: 0.137474:  88%|████████▊ | 88/100 [04:48<00:25,  2.11s/it]

Best trial: 84. Best value: 0.137474:  88%|████████▊ | 88/100 [04:49<00:25,  2.11s/it]

Best trial: 84. Best value: 0.137474:  89%|████████▉ | 89/100 [04:49<00:21,  2.00s/it]

Best trial: 84. Best value: 0.137474:  89%|████████▉ | 89/100 [04:52<00:21,  2.00s/it]

Best trial: 84. Best value: 0.137474:  90%|█████████ | 90/100 [04:52<00:20,  2.03s/it]

Best trial: 84. Best value: 0.137474:  90%|█████████ | 90/100 [04:54<00:20,  2.03s/it]

Best trial: 84. Best value: 0.137474:  91%|█████████ | 91/100 [04:54<00:18,  2.01s/it]

Best trial: 91. Best value: 0.137477:  91%|█████████ | 91/100 [04:56<00:18,  2.01s/it]

Best trial: 91. Best value: 0.137477:  92%|█████████▏| 92/100 [04:56<00:16,  2.04s/it]

Best trial: 91. Best value: 0.137477:  92%|█████████▏| 92/100 [04:57<00:16,  2.04s/it]

Best trial: 91. Best value: 0.137477:  93%|█████████▎| 93/100 [04:57<00:13,  1.96s/it]

Best trial: 91. Best value: 0.137477:  93%|█████████▎| 93/100 [05:00<00:13,  1.96s/it]

Best trial: 91. Best value: 0.137477:  94%|█████████▍| 94/100 [05:00<00:12,  2.05s/it]

Best trial: 91. Best value: 0.137477:  94%|█████████▍| 94/100 [05:02<00:12,  2.05s/it]

Best trial: 91. Best value: 0.137477:  95%|█████████▌| 95/100 [05:02<00:10,  2.16s/it]

Best trial: 91. Best value: 0.137477:  95%|█████████▌| 95/100 [05:04<00:10,  2.16s/it]

Best trial: 91. Best value: 0.137477:  96%|█████████▌| 96/100 [05:04<00:08,  2.21s/it]

Best trial: 91. Best value: 0.137477:  96%|█████████▌| 96/100 [05:06<00:08,  2.21s/it]

Best trial: 91. Best value: 0.137477:  97%|█████████▋| 97/100 [05:06<00:06,  2.08s/it]

Best trial: 91. Best value: 0.137477:  97%|█████████▋| 97/100 [05:09<00:06,  2.08s/it]

Best trial: 91. Best value: 0.137477:  98%|█████████▊| 98/100 [05:09<00:04,  2.17s/it]

Best trial: 91. Best value: 0.137477:  98%|█████████▊| 98/100 [05:11<00:04,  2.17s/it]

Best trial: 91. Best value: 0.137477:  99%|█████████▉| 99/100 [05:11<00:02,  2.23s/it]

Best trial: 99. Best value: 0.137521:  99%|█████████▉| 99/100 [05:13<00:02,  2.23s/it]

Best trial: 99. Best value: 0.137521: 100%|██████████| 100/100 [05:13<00:00,  2.32s/it]

Best trial: 99. Best value: 0.137521: 100%|██████████| 100/100 [05:13<00:00,  3.14s/it]

Best CV PR-AUC: 0.1375
Best params: {'n_estimators': 152, 'max_depth': 5, 'learning_rate': 0.01730280048834504, 'subsample': 0.8351869467439949, 'colsample_bytree': 0.8219142667790593, 'min_child_weight': 18, 'gamma': 4.309488925030828, 'scale_pos_weight': 11.21167556343957}

In [5]:
tuned_xgb = XGBClassifier(**study_xgb.best_params, eval_metric="aucpr", random_state=RANDOM_STATE, verbosity=0)
tuned_xgb.fit(X_train, y_train)

tuned_models = {}
tune_results = []

tuned_models["XGBoost (tuned)"] = tuned_xgb
tune_results.append(evaluate_model("XGBoost (tuned)", tuned_xgb, X_test, y_test, study_xgb.best_value, stage="tuned"))

2026/07/02 08:43:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

XGBoost (tuned): CV=0.1375 | Test AUC=0.6107 | PR-AUC=0.1396 | opt_thr=0.5700 | Precision=0.1352 | Recall=0.7969 | F1=0.2312

### 2.3.2 Random Forest

In [6]:
def objective_rf(trial):
    params = {
        "n_estimators":      trial.suggest_int("n_estimators", 100, 600),
        "max_depth":         trial.suggest_int("max_depth", 4, 30),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 30),
        "min_samples_leaf":  trial.suggest_int("min_samples_leaf", 1, 30),
        "max_features":      trial.suggest_float("max_features", 0.3, 1.0),
        "class_weight":      "balanced_subsample",
        "random_state":      RANDOM_STATE,
        "n_jobs":            -1,
    }
    model = RandomForestClassifier(**params)
    scores = cross_val_score(
        model, X_train, y_train,
        cv=StratifiedKFold(3, shuffle=True, random_state=RANDOM_STATE),
        scoring="average_precision", n_jobs=-1,
    )
    return scores.mean()

print("Tuning Random Forest with Optuna (100 trials, optimizing PR-AUC) ...")
study_rf = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study_rf.optimize(objective_rf, n_trials=N_TRIALS, show_progress_bar=True)
print(f"Best CV PR-AUC: {study_rf.best_value:.4f}")
print(f"Best params: {study_rf.best_params}")

Tuning Random Forest with Optuna (100 trials, optimizing PR-AUC) ...

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.129898:   0%|          | 0/100 [00:29<?, ?it/s]

Best trial: 0. Best value: 0.129898:   1%|          | 1/100 [00:29<48:25, 29.35s/it]

Best trial: 1. Best value: 0.136474:   1%|          | 1/100 [00:40<48:25, 29.35s/it]

Best trial: 1. Best value: 0.136474:   2%|▏         | 2/100 [00:40<30:15, 18.53s/it]

Best trial: 1. Best value: 0.136474:   2%|▏         | 2/100 [00:52<30:15, 18.53s/it]

Best trial: 1. Best value: 0.136474:   3%|▎         | 3/100 [00:52<25:25, 15.73s/it]

Best trial: 1. Best value: 0.136474:   3%|▎         | 3/100 [01:09<25:25, 15.73s/it]

Best trial: 1. Best value: 0.136474:   4%|▍         | 4/100 [01:09<25:50, 16.15s/it]

Best trial: 1. Best value: 0.136474:   4%|▍         | 4/100 [01:36<25:50, 16.15s/it]

Best trial: 1. Best value: 0.136474:   5%|▌         | 5/100 [01:36<32:00, 20.21s/it]

Best trial: 1. Best value: 0.136474:   5%|▌         | 5/100 [02:01<32:00, 20.21s/it]

Best trial: 1. Best value: 0.136474:   6%|▌         | 6/100 [02:01<33:57, 21.67s/it]

Best trial: 1. Best value: 0.136474:   6%|▌         | 6/100 [02:45<33:57, 21.67s/it]

Best trial: 1. Best value: 0.136474:   7%|▋         | 7/100 [02:45<45:05, 29.09s/it]

Best trial: 1. Best value: 0.136474:   7%|▋         | 7/100 [03:35<45:05, 29.09s/it]

Best trial: 1. Best value: 0.136474:   8%|▊         | 8/100 [03:35<54:43, 35.69s/it]

Best trial: 1. Best value: 0.136474:   8%|▊         | 8/100 [03:52<54:43, 35.69s/it]

Best trial: 1. Best value: 0.136474:   9%|▉         | 9/100 [03:52<45:03, 29.71s/it]

Best trial: 1. Best value: 0.136474:   9%|▉         | 9/100 [04:24<45:03, 29.71s/it]

Best trial: 1. Best value: 0.136474:  10%|█         | 10/100 [04:24<45:36, 30.41s/it]

Best trial: 1. Best value: 0.136474:  10%|█         | 10/100 [06:25<45:36, 30.41s/it]

Best trial: 1. Best value: 0.136474:  11%|█         | 11/100 [06:25<1:26:35, 58.37s/it]

Best trial: 1. Best value: 0.136474:  11%|█         | 11/100 [06:41<1:26:35, 58.37s/it]

Best trial: 1. Best value: 0.136474:  12%|█▏        | 12/100 [06:41<1:06:37, 45.43s/it]

Best trial: 1. Best value: 0.136474:  12%|█▏        | 12/100 [06:59<1:06:37, 45.43s/it]

Best trial: 1. Best value: 0.136474:  13%|█▎        | 13/100 [06:59<53:33, 36.94s/it]

Best trial: 13. Best value: 0.136527:  13%|█▎        | 13/100 [07:16<53:33, 36.94s/it]

Best trial: 13. Best value: 0.136527:  14%|█▍        | 14/100 [07:16<44:26, 31.01s/it]

Best trial: 13. Best value: 0.136527:  14%|█▍        | 14/100 [07:50<44:26, 31.01s/it]

Best trial: 13. Best value: 0.136527:  15%|█▌        | 15/100 [07:50<45:05, 31.83s/it]

Best trial: 13. Best value: 0.136527:  15%|█▌        | 15/100 [08:02<45:05, 31.83s/it]

Best trial: 13. Best value: 0.136527:  16%|█▌        | 16/100 [08:02<36:16, 25.91s/it]

Best trial: 13. Best value: 0.136527:  16%|█▌        | 16/100 [08:13<36:16, 25.91s/it]

Best trial: 13. Best value: 0.136527:  17%|█▋        | 17/100 [08:13<29:45, 21.51s/it]

Best trial: 13. Best value: 0.136527:  17%|█▋        | 17/100 [09:03<29:45, 21.51s/it]

Best trial: 13. Best value: 0.136527:  18%|█▊        | 18/100 [09:03<40:55, 29.95s/it]

Best trial: 13. Best value: 0.136527:  18%|█▊        | 18/100 [09:18<40:55, 29.95s/it]

Best trial: 13. Best value: 0.136527:  19%|█▉        | 19/100 [09:18<34:33, 25.60s/it]

Best trial: 13. Best value: 0.136527:  19%|█▉        | 19/100 [09:45<34:33, 25.60s/it]

Best trial: 13. Best value: 0.136527:  20%|██        | 20/100 [09:45<34:42, 26.03s/it]

Best trial: 13. Best value: 0.136527:  20%|██        | 20/100 [10:43<34:42, 26.03s/it]

Best trial: 13. Best value: 0.136527:  21%|██        | 21/100 [10:43<46:38, 35.42s/it]

Best trial: 13. Best value: 0.136527:  21%|██        | 21/100 [10:59<46:38, 35.42s/it]

Best trial: 13. Best value: 0.136527:  22%|██▏       | 22/100 [10:59<38:43, 29.79s/it]

Best trial: 13. Best value: 0.136527:  22%|██▏       | 22/100 [11:09<38:43, 29.79s/it]

Best trial: 13. Best value: 0.136527:  23%|██▎       | 23/100 [11:09<30:29, 23.76s/it]

Best trial: 13. Best value: 0.136527:  23%|██▎       | 23/100 [11:32<30:29, 23.76s/it]

Best trial: 13. Best value: 0.136527:  24%|██▍       | 24/100 [11:32<29:48, 23.53s/it]

Best trial: 13. Best value: 0.136527:  24%|██▍       | 24/100 [11:50<29:48, 23.53s/it]

Best trial: 13. Best value: 0.136527:  25%|██▌       | 25/100 [11:50<27:21, 21.88s/it]

Best trial: 13. Best value: 0.136527:  25%|██▌       | 25/100 [12:08<27:21, 21.88s/it]

Best trial: 13. Best value: 0.136527:  26%|██▌       | 26/100 [12:08<25:26, 20.63s/it]

Best trial: 13. Best value: 0.136527:  26%|██▌       | 26/100 [12:28<25:26, 20.63s/it]

Best trial: 13. Best value: 0.136527:  27%|██▋       | 27/100 [12:28<24:54, 20.47s/it]

Best trial: 27. Best value: 0.136564:  27%|██▋       | 27/100 [12:39<24:54, 20.47s/it]

Best trial: 27. Best value: 0.136564:  28%|██▊       | 28/100 [12:39<21:11, 17.66s/it]

Best trial: 27. Best value: 0.136564:  28%|██▊       | 28/100 [12:58<21:11, 17.66s/it]

Best trial: 27. Best value: 0.136564:  29%|██▉       | 29/100 [12:58<21:31, 18.19s/it]

Best trial: 27. Best value: 0.136564:  29%|██▉       | 29/100 [14:03<21:31, 18.19s/it]

Best trial: 27. Best value: 0.136564:  30%|███       | 30/100 [14:03<37:40, 32.29s/it]

Best trial: 27. Best value: 0.136564:  30%|███       | 30/100 [14:13<37:40, 32.29s/it]

Best trial: 27. Best value: 0.136564:  31%|███       | 31/100 [14:13<29:07, 25.33s/it]

Best trial: 27. Best value: 0.136564:  31%|███       | 31/100 [14:24<29:07, 25.33s/it]

Best trial: 27. Best value: 0.136564:  32%|███▏      | 32/100 [14:24<23:52, 21.06s/it]

Best trial: 27. Best value: 0.136564:  32%|███▏      | 32/100 [14:37<23:52, 21.06s/it]

Best trial: 27. Best value: 0.136564:  33%|███▎      | 33/100 [14:37<20:47, 18.61s/it]

Best trial: 27. Best value: 0.136564:  33%|███▎      | 33/100 [14:56<20:47, 18.61s/it]

Best trial: 27. Best value: 0.136564:  34%|███▍      | 34/100 [14:56<20:43, 18.83s/it]

Best trial: 27. Best value: 0.136564:  34%|███▍      | 34/100 [15:04<20:43, 18.83s/it]

Best trial: 27. Best value: 0.136564:  35%|███▌      | 35/100 [15:04<16:59, 15.68s/it]

Best trial: 27. Best value: 0.136564:  35%|███▌      | 35/100 [15:43<16:59, 15.68s/it]

Best trial: 27. Best value: 0.136564:  36%|███▌      | 36/100 [15:43<23:59, 22.49s/it]

Best trial: 27. Best value: 0.136564:  36%|███▌      | 36/100 [16:00<23:59, 22.49s/it]

Best trial: 27. Best value: 0.136564:  37%|███▋      | 37/100 [16:00<22:05, 21.05s/it]

Best trial: 27. Best value: 0.136564:  37%|███▋      | 37/100 [16:34<22:05, 21.05s/it]

Best trial: 27. Best value: 0.136564:  38%|███▊      | 38/100 [16:34<25:44, 24.91s/it]

Best trial: 27. Best value: 0.136564:  38%|███▊      | 38/100 [16:43<25:44, 24.91s/it]

Best trial: 27. Best value: 0.136564:  39%|███▉      | 39/100 [16:43<20:26, 20.10s/it]

Best trial: 27. Best value: 0.136564:  39%|███▉      | 39/100 [17:09<20:26, 20.10s/it]

Best trial: 27. Best value: 0.136564:  40%|████      | 40/100 [17:09<21:48, 21.80s/it]

Best trial: 27. Best value: 0.136564:  40%|████      | 40/100 [17:15<21:48, 21.80s/it]

Best trial: 27. Best value: 0.136564:  41%|████      | 41/100 [17:15<16:53, 17.17s/it]

Best trial: 27. Best value: 0.136564:  41%|████      | 41/100 [17:26<16:53, 17.17s/it]

Best trial: 27. Best value: 0.136564:  42%|████▏     | 42/100 [17:26<14:43, 15.23s/it]

Best trial: 42. Best value: 0.13661:  42%|████▏     | 42/100 [17:42<14:43, 15.23s/it]

Best trial: 42. Best value: 0.13661:  43%|████▎     | 43/100 [17:42<14:48, 15.58s/it]

Best trial: 43. Best value: 0.13671:  43%|████▎     | 43/100 [17:59<14:48, 15.58s/it]

Best trial: 43. Best value: 0.13671:  44%|████▍     | 44/100 [17:59<14:44, 15.79s/it]

Best trial: 43. Best value: 0.13671:  44%|████▍     | 44/100 [18:18<14:44, 15.79s/it]

Best trial: 43. Best value: 0.13671:  45%|████▌     | 45/100 [18:18<15:31, 16.94s/it]

Best trial: 43. Best value: 0.13671:  45%|████▌     | 45/100 [18:40<15:31, 16.94s/it]

Best trial: 43. Best value: 0.13671:  46%|████▌     | 46/100 [18:40<16:39, 18.51s/it]

Best trial: 43. Best value: 0.13671:  46%|████▌     | 46/100 [18:53<16:39, 18.51s/it]

Best trial: 43. Best value: 0.13671:  47%|████▋     | 47/100 [18:53<14:51, 16.81s/it]

Best trial: 47. Best value: 0.136721:  47%|████▋     | 47/100 [19:07<14:51, 16.81s/it]

Best trial: 47. Best value: 0.136721:  48%|████▊     | 48/100 [19:07<13:52, 16.02s/it]

Best trial: 47. Best value: 0.136721:  48%|████▊     | 48/100 [19:26<13:52, 16.02s/it]

Best trial: 47. Best value: 0.136721:  49%|████▉     | 49/100 [19:26<14:20, 16.86s/it]

Best trial: 47. Best value: 0.136721:  49%|████▉     | 49/100 [19:42<14:20, 16.86s/it]

Best trial: 47. Best value: 0.136721:  50%|█████     | 50/100 [19:42<13:52, 16.66s/it]

Best trial: 47. Best value: 0.136721:  50%|█████     | 50/100 [20:02<13:52, 16.66s/it]

Best trial: 47. Best value: 0.136721:  51%|█████     | 51/100 [20:02<14:23, 17.62s/it]

Best trial: 51. Best value: 0.136746:  51%|█████     | 51/100 [20:16<14:23, 17.62s/it]

Best trial: 51. Best value: 0.136746:  52%|█████▏    | 52/100 [20:16<13:05, 16.37s/it]

Best trial: 51. Best value: 0.136746:  52%|█████▏    | 52/100 [20:32<13:05, 16.37s/it]

Best trial: 51. Best value: 0.136746:  53%|█████▎    | 53/100 [20:32<12:52, 16.43s/it]

Best trial: 51. Best value: 0.136746:  53%|█████▎    | 53/100 [20:52<12:52, 16.43s/it]

Best trial: 51. Best value: 0.136746:  54%|█████▍    | 54/100 [20:52<13:18, 17.36s/it]

Best trial: 51. Best value: 0.136746:  54%|█████▍    | 54/100 [21:10<13:18, 17.36s/it]

Best trial: 51. Best value: 0.136746:  55%|█████▌    | 55/100 [21:10<13:12, 17.62s/it]

Best trial: 51. Best value: 0.136746:  55%|█████▌    | 55/100 [21:20<13:12, 17.62s/it]

Best trial: 51. Best value: 0.136746:  56%|█████▌    | 56/100 [21:20<11:19, 15.45s/it]

Best trial: 56. Best value: 0.136828:  56%|█████▌    | 56/100 [21:42<11:19, 15.45s/it]

Best trial: 56. Best value: 0.136828:  57%|█████▋    | 57/100 [21:42<12:21, 17.25s/it]

Best trial: 56. Best value: 0.136828:  57%|█████▋    | 57/100 [22:06<12:21, 17.25s/it]

Best trial: 56. Best value: 0.136828:  58%|█████▊    | 58/100 [22:06<13:27, 19.22s/it]

Best trial: 56. Best value: 0.136828:  58%|█████▊    | 58/100 [22:35<13:27, 19.22s/it]

Best trial: 56. Best value: 0.136828:  59%|█████▉    | 59/100 [22:35<15:13, 22.28s/it]

Best trial: 56. Best value: 0.136828:  59%|█████▉    | 59/100 [22:47<15:13, 22.28s/it]

Best trial: 56. Best value: 0.136828:  60%|██████    | 60/100 [22:47<12:51, 19.28s/it]

Best trial: 56. Best value: 0.136828:  60%|██████    | 60/100 [23:31<12:51, 19.28s/it]

Best trial: 56. Best value: 0.136828:  61%|██████    | 61/100 [23:31<17:12, 26.49s/it]

Best trial: 56. Best value: 0.136828:  61%|██████    | 61/100 [23:55<17:12, 26.49s/it]

Best trial: 56. Best value: 0.136828:  62%|██████▏   | 62/100 [23:55<16:23, 25.88s/it]

Best trial: 56. Best value: 0.136828:  62%|██████▏   | 62/100 [24:23<16:23, 25.88s/it]

Best trial: 56. Best value: 0.136828:  63%|██████▎   | 63/100 [24:23<16:21, 26.54s/it]

Best trial: 56. Best value: 0.136828:  63%|██████▎   | 63/100 [24:51<16:21, 26.54s/it]

Best trial: 56. Best value: 0.136828:  64%|██████▍   | 64/100 [24:51<16:13, 27.05s/it]

Best trial: 56. Best value: 0.136828:  64%|██████▍   | 64/100 [25:04<16:13, 27.05s/it]

Best trial: 56. Best value: 0.136828:  65%|██████▌   | 65/100 [25:04<13:12, 22.66s/it]

Best trial: 56. Best value: 0.136828:  65%|██████▌   | 65/100 [25:26<13:12, 22.66s/it]

Best trial: 56. Best value: 0.136828:  66%|██████▌   | 66/100 [25:26<12:46, 22.54s/it]

Best trial: 56. Best value: 0.136828:  66%|██████▌   | 66/100 [26:11<12:46, 22.54s/it]

Best trial: 56. Best value: 0.136828:  67%|██████▋   | 67/100 [26:11<16:00, 29.10s/it]

Best trial: 56. Best value: 0.136828:  67%|██████▋   | 67/100 [26:30<16:00, 29.10s/it]

Best trial: 56. Best value: 0.136828:  68%|██████▊   | 68/100 [26:30<14:02, 26.32s/it]

Best trial: 56. Best value: 0.136828:  68%|██████▊   | 68/100 [26:47<14:02, 26.32s/it]

Best trial: 56. Best value: 0.136828:  69%|██████▉   | 69/100 [26:47<12:02, 23.30s/it]

Best trial: 56. Best value: 0.136828:  69%|██████▉   | 69/100 [27:47<12:02, 23.30s/it]

Best trial: 56. Best value: 0.136828:  70%|███████   | 70/100 [27:47<17:14, 34.47s/it]

Best trial: 56. Best value: 0.136828:  70%|███████   | 70/100 [28:13<17:14, 34.47s/it]

Best trial: 56. Best value: 0.136828:  71%|███████   | 71/100 [28:13<15:25, 31.90s/it]

Best trial: 56. Best value: 0.136828:  71%|███████   | 71/100 [28:38<15:25, 31.90s/it]

Best trial: 56. Best value: 0.136828:  72%|███████▏  | 72/100 [28:38<13:52, 29.72s/it]

Best trial: 56. Best value: 0.136828:  72%|███████▏  | 72/100 [29:03<13:52, 29.72s/it]

Best trial: 56. Best value: 0.136828:  73%|███████▎  | 73/100 [29:03<12:43, 28.29s/it]

Best trial: 56. Best value: 0.136828:  73%|███████▎  | 73/100 [29:25<12:43, 28.29s/it]

Best trial: 56. Best value: 0.136828:  74%|███████▍  | 74/100 [29:25<11:26, 26.42s/it]

Best trial: 56. Best value: 0.136828:  74%|███████▍  | 74/100 [29:45<11:26, 26.42s/it]

Best trial: 56. Best value: 0.136828:  75%|███████▌  | 75/100 [29:45<10:14, 24.60s/it]

Best trial: 56. Best value: 0.136828:  75%|███████▌  | 75/100 [30:15<10:14, 24.60s/it]

Best trial: 56. Best value: 0.136828:  76%|███████▌  | 76/100 [30:15<10:25, 26.04s/it]

Best trial: 56. Best value: 0.136828:  76%|███████▌  | 76/100 [30:34<10:25, 26.04s/it]

Best trial: 56. Best value: 0.136828:  77%|███████▋  | 77/100 [30:34<09:15, 24.14s/it]

Best trial: 56. Best value: 0.136828:  77%|███████▋  | 77/100 [31:06<09:15, 24.14s/it]

Best trial: 56. Best value: 0.136828:  78%|███████▊  | 78/100 [31:06<09:44, 26.57s/it]

Best trial: 56. Best value: 0.136828:  78%|███████▊  | 78/100 [31:37<09:44, 26.57s/it]

Best trial: 56. Best value: 0.136828:  79%|███████▉  | 79/100 [31:37<09:42, 27.76s/it]

Best trial: 56. Best value: 0.136828:  79%|███████▉  | 79/100 [32:26<09:42, 27.76s/it]

Best trial: 56. Best value: 0.136828:  80%|████████  | 80/100 [32:26<11:23, 34.16s/it]

Best trial: 56. Best value: 0.136828:  80%|████████  | 80/100 [32:52<11:23, 34.16s/it]

Best trial: 56. Best value: 0.136828:  81%|████████  | 81/100 [32:52<10:04, 31.83s/it]

Best trial: 56. Best value: 0.136828:  81%|████████  | 81/100 [33:18<10:04, 31.83s/it]

Best trial: 56. Best value: 0.136828:  82%|████████▏ | 82/100 [33:18<09:00, 30.02s/it]

Best trial: 56. Best value: 0.136828:  82%|████████▏ | 82/100 [33:39<09:00, 30.02s/it]

Best trial: 56. Best value: 0.136828:  83%|████████▎ | 83/100 [33:39<07:45, 27.36s/it]

Best trial: 56. Best value: 0.136828:  83%|████████▎ | 83/100 [34:03<07:45, 27.36s/it]

Best trial: 56. Best value: 0.136828:  84%|████████▍ | 84/100 [34:03<06:59, 26.21s/it]

Best trial: 56. Best value: 0.136828:  84%|████████▍ | 84/100 [34:28<06:59, 26.21s/it]

Best trial: 56. Best value: 0.136828:  85%|████████▌ | 85/100 [34:28<06:26, 25.76s/it]

Best trial: 56. Best value: 0.136828:  85%|████████▌ | 85/100 [34:53<06:26, 25.76s/it]

Best trial: 56. Best value: 0.136828:  86%|████████▌ | 86/100 [34:53<05:59, 25.71s/it]

Best trial: 56. Best value: 0.136828:  86%|████████▌ | 86/100 [35:10<05:59, 25.71s/it]

Best trial: 56. Best value: 0.136828:  87%|████████▋ | 87/100 [35:10<04:57, 22.91s/it]

Best trial: 56. Best value: 0.136828:  87%|████████▋ | 87/100 [35:25<04:57, 22.91s/it]

Best trial: 56. Best value: 0.136828:  88%|████████▊ | 88/100 [35:25<04:08, 20.73s/it]

Best trial: 56. Best value: 0.136828:  88%|████████▊ | 88/100 [35:47<04:08, 20.73s/it]

Best trial: 56. Best value: 0.136828:  89%|████████▉ | 89/100 [35:47<03:50, 20.99s/it]

Best trial: 56. Best value: 0.136828:  89%|████████▉ | 89/100 [35:59<03:50, 20.99s/it]

Best trial: 56. Best value: 0.136828:  90%|█████████ | 90/100 [35:59<03:02, 18.29s/it]

Best trial: 56. Best value: 0.136828:  90%|█████████ | 90/100 [38:06<03:02, 18.29s/it]

Best trial: 56. Best value: 0.136828:  91%|█████████ | 91/100 [38:06<07:38, 50.89s/it]

Best trial: 56. Best value: 0.136828:  91%|█████████ | 91/100 [38:35<07:38, 50.89s/it]

Best trial: 56. Best value: 0.136828:  92%|█████████▏| 92/100 [38:35<05:54, 44.27s/it]

Best trial: 56. Best value: 0.136828:  92%|█████████▏| 92/100 [39:13<05:54, 44.27s/it]

Best trial: 56. Best value: 0.136828:  93%|█████████▎| 93/100 [39:13<04:56, 42.38s/it]

Best trial: 56. Best value: 0.136828:  93%|█████████▎| 93/100 [39:36<04:56, 42.38s/it]

Best trial: 56. Best value: 0.136828:  94%|█████████▍| 94/100 [39:36<03:40, 36.79s/it]

Best trial: 56. Best value: 0.136828:  94%|█████████▍| 94/100 [40:06<03:40, 36.79s/it]

Best trial: 56. Best value: 0.136828:  95%|█████████▌| 95/100 [40:06<02:53, 34.77s/it]

Best trial: 56. Best value: 0.136828:  95%|█████████▌| 95/100 [40:32<02:53, 34.77s/it]

Best trial: 56. Best value: 0.136828:  96%|█████████▌| 96/100 [40:32<02:08, 32.16s/it]

Best trial: 56. Best value: 0.136828:  96%|█████████▌| 96/100 [41:16<02:08, 32.16s/it]

Best trial: 56. Best value: 0.136828:  97%|█████████▋| 97/100 [41:16<01:46, 35.57s/it]

Best trial: 56. Best value: 0.136828:  97%|█████████▋| 97/100 [41:33<01:46, 35.57s/it]

Best trial: 56. Best value: 0.136828:  98%|█████████▊| 98/100 [41:33<00:59, 29.96s/it]

Best trial: 56. Best value: 0.136828:  98%|█████████▊| 98/100 [42:07<00:59, 29.96s/it]

Best trial: 56. Best value: 0.136828:  99%|█████████▉| 99/100 [42:07<00:31, 31.14s/it]

Best trial: 56. Best value: 0.136828:  99%|█████████▉| 99/100 [42:38<00:31, 31.14s/it]

Best trial: 56. Best value: 0.136828: 100%|██████████| 100/100 [42:38<00:00, 31.15s/it]

Best trial: 56. Best value: 0.136828: 100%|██████████| 100/100 [42:38<00:00, 25.58s/it]

Best CV PR-AUC: 0.1368
Best params: {'n_estimators': 240, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 30, 'max_features': 0.9014004499270568}

In [7]:
tuned_rf = RandomForestClassifier(
    **study_rf.best_params, class_weight="balanced_subsample",
    random_state=RANDOM_STATE, n_jobs=-1,
)
tuned_rf.fit(X_train, y_train)

tuned_models["Random Forest (tuned)"] = tuned_rf
tune_results.append(evaluate_model("Random Forest (tuned)", tuned_rf, X_test, y_test, study_rf.best_value, stage="tuned"))

Random Forest (tuned): CV=0.1368 | Test AUC=0.6103 | PR-AUC=0.1399 | opt_thr=0.4708 | Precision=0.1347 | Recall=0.7976 | F1=0.2305

2026/07/02 09:26:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

### 2.3.3 LightGBM

In [8]:
def objective_lgbm(trial):
    params = {
        "n_estimators":     trial.suggest_int("n_estimators", 100, 600),
        "max_depth":        trial.suggest_int("max_depth", 3, 12),
        "num_leaves":       trial.suggest_int("num_leaves", 15, 255),
        "learning_rate":    trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample":        trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 5.0, 20.0),
        "random_state":     RANDOM_STATE,
        "verbosity":        -1,
    }
    model = LGBMClassifier(**params)
    scores = cross_val_score(
        model, X_train, y_train,
        cv=StratifiedKFold(3, shuffle=True, random_state=RANDOM_STATE),
        scoring="average_precision", n_jobs=-1,
    )
    return scores.mean()

print("Tuning LightGBM with Optuna (100 trials, optimizing PR-AUC) ...")
study_lgbm = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study_lgbm.optimize(objective_lgbm, n_trials=N_TRIALS, show_progress_bar=True)
print(f"Best CV PR-AUC: {study_lgbm.best_value:.4f}")
print(f"Best params: {study_lgbm.best_params}")

Tuning LightGBM with Optuna (100 trials, optimizing PR-AUC) ...

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.123201:   0%|          | 0/100 [00:15<?, ?it/s]

Best trial: 0. Best value: 0.123201:   1%|          | 1/100 [00:15<26:17, 15.94s/it]

Best trial: 1. Best value: 0.124796:   1%|          | 1/100 [00:22<26:17, 15.94s/it]

Best trial: 1. Best value: 0.124796:   2%|▏         | 2/100 [00:22<17:27, 10.69s/it]

Best trial: 2. Best value: 0.130454:   2%|▏         | 2/100 [00:30<17:27, 10.69s/it]

Best trial: 2. Best value: 0.130454:   3%|▎         | 3/100 [00:30<15:00,  9.28s/it]

Best trial: 2. Best value: 0.130454:   3%|▎         | 3/100 [00:38<15:00,  9.28s/it]

Best trial: 2. Best value: 0.130454:   4%|▍         | 4/100 [00:38<13:58,  8.74s/it]

Best trial: 2. Best value: 0.130454:   4%|▍         | 4/100 [00:44<13:58,  8.74s/it]

Best trial: 2. Best value: 0.130454:   5%|▌         | 5/100 [00:44<12:25,  7.85s/it]

Best trial: 2. Best value: 0.130454:   5%|▌         | 5/100 [00:46<12:25,  7.85s/it]

Best trial: 2. Best value: 0.130454:   6%|▌         | 6/100 [00:46<09:15,  5.91s/it]

Best trial: 2. Best value: 0.130454:   6%|▌         | 6/100 [00:50<09:15,  5.91s/it]

Best trial: 2. Best value: 0.130454:   7%|▋         | 7/100 [00:50<08:07,  5.24s/it]

Best trial: 7. Best value: 0.134916:   7%|▋         | 7/100 [00:52<08:07,  5.24s/it]

Best trial: 7. Best value: 0.134916:   8%|▊         | 8/100 [00:52<06:14,  4.08s/it]

Best trial: 7. Best value: 0.134916:   8%|▊         | 8/100 [00:56<06:14,  4.08s/it]

Best trial: 7. Best value: 0.134916:   9%|▉         | 9/100 [00:56<06:16,  4.14s/it]

Best trial: 7. Best value: 0.134916:   9%|▉         | 9/100 [01:01<06:16,  4.14s/it]

Best trial: 7. Best value: 0.134916:  10%|█         | 10/100 [01:01<06:30,  4.34s/it]

Best trial: 10. Best value: 0.135428:  10%|█         | 10/100 [01:05<06:30,  4.34s/it]

Best trial: 10. Best value: 0.135428:  11%|█         | 11/100 [01:05<06:29,  4.37s/it]

Best trial: 10. Best value: 0.135428:  11%|█         | 11/100 [01:11<06:29,  4.37s/it]

Best trial: 10. Best value: 0.135428:  12%|█▏        | 12/100 [01:11<07:05,  4.84s/it]

Best trial: 12. Best value: 0.135544:  12%|█▏        | 12/100 [01:17<07:05,  4.84s/it]

Best trial: 12. Best value: 0.135544:  13%|█▎        | 13/100 [01:17<07:22,  5.09s/it]

Best trial: 12. Best value: 0.135544:  13%|█▎        | 13/100 [01:25<07:22,  5.09s/it]

Best trial: 12. Best value: 0.135544:  14%|█▍        | 14/100 [01:25<08:45,  6.11s/it]

Best trial: 12. Best value: 0.135544:  14%|█▍        | 14/100 [01:30<08:45,  6.11s/it]

Best trial: 12. Best value: 0.135544:  15%|█▌        | 15/100 [01:30<07:58,  5.63s/it]

Best trial: 12. Best value: 0.135544:  15%|█▌        | 15/100 [01:38<07:58,  5.63s/it]

Best trial: 12. Best value: 0.135544:  16%|█▌        | 16/100 [01:38<08:56,  6.38s/it]

Best trial: 12. Best value: 0.135544:  16%|█▌        | 16/100 [01:45<08:56,  6.38s/it]

Best trial: 12. Best value: 0.135544:  17%|█▋        | 17/100 [01:45<09:01,  6.53s/it]

Best trial: 12. Best value: 0.135544:  17%|█▋        | 17/100 [01:49<09:01,  6.53s/it]

Best trial: 12. Best value: 0.135544:  18%|█▊        | 18/100 [01:49<07:45,  5.68s/it]

Best trial: 12. Best value: 0.135544:  18%|█▊        | 18/100 [01:54<07:45,  5.68s/it]

Best trial: 12. Best value: 0.135544:  19%|█▉        | 19/100 [01:54<07:39,  5.67s/it]

Best trial: 12. Best value: 0.135544:  19%|█▉        | 19/100 [02:00<07:39,  5.67s/it]

Best trial: 12. Best value: 0.135544:  20%|██        | 20/100 [02:00<07:27,  5.59s/it]

Best trial: 12. Best value: 0.135544:  20%|██        | 20/100 [02:07<07:27,  5.59s/it]

Best trial: 12. Best value: 0.135544:  21%|██        | 21/100 [02:07<07:53,  5.99s/it]

Best trial: 12. Best value: 0.135544:  21%|██        | 21/100 [02:11<07:53,  5.99s/it]

Best trial: 12. Best value: 0.135544:  22%|██▏       | 22/100 [02:11<07:02,  5.42s/it]

Best trial: 22. Best value: 0.13565:  22%|██▏       | 22/100 [02:15<07:02,  5.42s/it]

Best trial: 22. Best value: 0.13565:  23%|██▎       | 23/100 [02:15<06:32,  5.10s/it]

Best trial: 22. Best value: 0.13565:  23%|██▎       | 23/100 [02:20<06:32,  5.10s/it]

Best trial: 22. Best value: 0.13565:  24%|██▍       | 24/100 [02:20<06:32,  5.16s/it]

Best trial: 22. Best value: 0.13565:  24%|██▍       | 24/100 [02:24<06:32,  5.16s/it]

Best trial: 22. Best value: 0.13565:  25%|██▌       | 25/100 [02:24<05:52,  4.70s/it]

Best trial: 22. Best value: 0.13565:  25%|██▌       | 25/100 [02:30<05:52,  4.70s/it]

Best trial: 22. Best value: 0.13565:  26%|██▌       | 26/100 [02:30<06:20,  5.14s/it]

Best trial: 22. Best value: 0.13565:  26%|██▌       | 26/100 [02:38<06:20,  5.14s/it]

Best trial: 22. Best value: 0.13565:  27%|██▋       | 27/100 [02:38<07:19,  6.02s/it]

Best trial: 22. Best value: 0.13565:  27%|██▋       | 27/100 [02:42<07:19,  6.02s/it]

Best trial: 22. Best value: 0.13565:  28%|██▊       | 28/100 [02:42<06:25,  5.35s/it]

Best trial: 22. Best value: 0.13565:  28%|██▊       | 28/100 [02:50<06:25,  5.35s/it]

Best trial: 22. Best value: 0.13565:  29%|██▉       | 29/100 [02:50<07:25,  6.28s/it]

Best trial: 22. Best value: 0.13565:  29%|██▉       | 29/100 [02:55<07:25,  6.28s/it]

Best trial: 22. Best value: 0.13565:  30%|███       | 30/100 [02:55<06:46,  5.81s/it]

Best trial: 22. Best value: 0.13565:  30%|███       | 30/100 [03:00<06:46,  5.81s/it]

Best trial: 22. Best value: 0.13565:  31%|███       | 31/100 [03:00<06:15,  5.44s/it]

Best trial: 22. Best value: 0.13565:  31%|███       | 31/100 [03:04<06:15,  5.44s/it]

Best trial: 22. Best value: 0.13565:  32%|███▏      | 32/100 [03:04<05:43,  5.05s/it]

Best trial: 22. Best value: 0.13565:  32%|███▏      | 32/100 [03:08<05:43,  5.05s/it]

Best trial: 22. Best value: 0.13565:  33%|███▎      | 33/100 [03:08<05:19,  4.77s/it]

Best trial: 22. Best value: 0.13565:  33%|███▎      | 33/100 [03:13<05:19,  4.77s/it]

Best trial: 22. Best value: 0.13565:  34%|███▍      | 34/100 [03:13<05:12,  4.73s/it]

Best trial: 22. Best value: 0.13565:  34%|███▍      | 34/100 [03:19<05:12,  4.73s/it]

Best trial: 22. Best value: 0.13565:  35%|███▌      | 35/100 [03:19<05:44,  5.29s/it]

Best trial: 22. Best value: 0.13565:  35%|███▌      | 35/100 [03:23<05:44,  5.29s/it]

Best trial: 22. Best value: 0.13565:  36%|███▌      | 36/100 [03:23<05:08,  4.82s/it]

Best trial: 36. Best value: 0.135757:  36%|███▌      | 36/100 [03:27<05:08,  4.82s/it]

Best trial: 36. Best value: 0.135757:  37%|███▋      | 37/100 [03:27<04:51,  4.62s/it]

Best trial: 36. Best value: 0.135757:  37%|███▋      | 37/100 [03:32<04:51,  4.62s/it]

Best trial: 36. Best value: 0.135757:  38%|███▊      | 38/100 [03:32<04:52,  4.71s/it]

Best trial: 36. Best value: 0.135757:  38%|███▊      | 38/100 [03:36<04:52,  4.71s/it]

Best trial: 36. Best value: 0.135757:  39%|███▉      | 39/100 [03:36<04:40,  4.60s/it]

Best trial: 36. Best value: 0.135757:  39%|███▉      | 39/100 [03:44<04:40,  4.60s/it]

Best trial: 36. Best value: 0.135757:  40%|████      | 40/100 [03:44<05:39,  5.66s/it]

Best trial: 36. Best value: 0.135757:  40%|████      | 40/100 [03:48<05:39,  5.66s/it]

Best trial: 36. Best value: 0.135757:  41%|████      | 41/100 [03:48<05:03,  5.14s/it]

Best trial: 36. Best value: 0.135757:  41%|████      | 41/100 [03:53<05:03,  5.14s/it]

Best trial: 36. Best value: 0.135757:  42%|████▏     | 42/100 [03:53<04:45,  4.92s/it]

Best trial: 36. Best value: 0.135757:  42%|████▏     | 42/100 [03:56<04:45,  4.92s/it]

Best trial: 36. Best value: 0.135757:  43%|████▎     | 43/100 [03:56<04:10,  4.39s/it]

Best trial: 36. Best value: 0.135757:  43%|████▎     | 43/100 [04:00<04:10,  4.39s/it]

Best trial: 36. Best value: 0.135757:  44%|████▍     | 44/100 [04:00<03:53,  4.18s/it]

Best trial: 36. Best value: 0.135757:  44%|████▍     | 44/100 [04:08<03:53,  4.18s/it]

Best trial: 36. Best value: 0.135757:  45%|████▌     | 45/100 [04:08<05:04,  5.55s/it]

Best trial: 36. Best value: 0.135757:  45%|████▌     | 45/100 [04:12<05:04,  5.55s/it]

Best trial: 36. Best value: 0.135757:  46%|████▌     | 46/100 [04:12<04:24,  4.90s/it]

Best trial: 36. Best value: 0.135757:  46%|████▌     | 46/100 [04:14<04:24,  4.90s/it]

Best trial: 36. Best value: 0.135757:  47%|████▋     | 47/100 [04:14<03:32,  4.02s/it]

Best trial: 36. Best value: 0.135757:  47%|████▋     | 47/100 [04:17<03:32,  4.02s/it]

Best trial: 36. Best value: 0.135757:  48%|████▊     | 48/100 [04:17<03:23,  3.91s/it]

Best trial: 36. Best value: 0.135757:  48%|████▊     | 48/100 [04:23<03:23,  3.91s/it]

Best trial: 36. Best value: 0.135757:  49%|████▉     | 49/100 [04:24<03:53,  4.57s/it]

Best trial: 36. Best value: 0.135757:  49%|████▉     | 49/100 [04:27<03:53,  4.57s/it]

Best trial: 36. Best value: 0.135757:  50%|█████     | 50/100 [04:27<03:31,  4.24s/it]

Best trial: 36. Best value: 0.135757:  50%|█████     | 50/100 [04:30<03:31,  4.24s/it]

Best trial: 36. Best value: 0.135757:  51%|█████     | 51/100 [04:30<03:13,  3.95s/it]

Best trial: 36. Best value: 0.135757:  51%|█████     | 51/100 [04:34<03:13,  3.95s/it]

Best trial: 36. Best value: 0.135757:  52%|█████▏    | 52/100 [04:34<03:10,  3.97s/it]

Best trial: 36. Best value: 0.135757:  52%|█████▏    | 52/100 [04:39<03:10,  3.97s/it]

Best trial: 36. Best value: 0.135757:  53%|█████▎    | 53/100 [04:39<03:17,  4.20s/it]

Best trial: 36. Best value: 0.135757:  53%|█████▎    | 53/100 [04:43<03:17,  4.20s/it]

Best trial: 36. Best value: 0.135757:  54%|█████▍    | 54/100 [04:43<03:13,  4.21s/it]

Best trial: 36. Best value: 0.135757:  54%|█████▍    | 54/100 [04:47<03:13,  4.21s/it]

Best trial: 36. Best value: 0.135757:  55%|█████▌    | 55/100 [04:47<03:08,  4.19s/it]

Best trial: 36. Best value: 0.135757:  55%|█████▌    | 55/100 [04:51<03:08,  4.19s/it]

Best trial: 36. Best value: 0.135757:  56%|█████▌    | 56/100 [04:51<02:57,  4.03s/it]

Best trial: 36. Best value: 0.135757:  56%|█████▌    | 56/100 [04:56<02:57,  4.03s/it]

Best trial: 36. Best value: 0.135757:  57%|█████▋    | 57/100 [04:56<03:09,  4.41s/it]

Best trial: 36. Best value: 0.135757:  57%|█████▋    | 57/100 [05:00<03:09,  4.41s/it]

Best trial: 36. Best value: 0.135757:  58%|█████▊    | 58/100 [05:00<03:01,  4.32s/it]

Best trial: 36. Best value: 0.135757:  58%|█████▊    | 58/100 [05:04<03:01,  4.32s/it]

Best trial: 36. Best value: 0.135757:  59%|█████▉    | 59/100 [05:04<02:42,  3.97s/it]

Best trial: 36. Best value: 0.135757:  59%|█████▉    | 59/100 [05:07<02:42,  3.97s/it]

Best trial: 36. Best value: 0.135757:  60%|██████    | 60/100 [05:07<02:27,  3.68s/it]

Best trial: 36. Best value: 0.135757:  60%|██████    | 60/100 [05:10<02:27,  3.68s/it]

Best trial: 36. Best value: 0.135757:  61%|██████    | 61/100 [05:10<02:19,  3.58s/it]

Best trial: 36. Best value: 0.135757:  61%|██████    | 61/100 [05:14<02:19,  3.58s/it]

Best trial: 36. Best value: 0.135757:  62%|██████▏   | 62/100 [05:14<02:19,  3.67s/it]

Best trial: 36. Best value: 0.135757:  62%|██████▏   | 62/100 [05:16<02:19,  3.67s/it]

Best trial: 36. Best value: 0.135757:  63%|██████▎   | 63/100 [05:16<02:01,  3.28s/it]

Best trial: 36. Best value: 0.135757:  63%|██████▎   | 63/100 [05:19<02:01,  3.28s/it]

Best trial: 36. Best value: 0.135757:  64%|██████▍   | 64/100 [05:19<01:56,  3.24s/it]

Best trial: 36. Best value: 0.135757:  64%|██████▍   | 64/100 [05:22<01:56,  3.24s/it]

Best trial: 36. Best value: 0.135757:  65%|██████▌   | 65/100 [05:22<01:44,  2.98s/it]

Best trial: 36. Best value: 0.135757:  65%|██████▌   | 65/100 [05:24<01:44,  2.98s/it]

Best trial: 36. Best value: 0.135757:  66%|██████▌   | 66/100 [05:24<01:33,  2.74s/it]

Best trial: 36. Best value: 0.135757:  66%|██████▌   | 66/100 [05:27<01:33,  2.74s/it]

Best trial: 36. Best value: 0.135757:  67%|██████▋   | 67/100 [05:27<01:34,  2.86s/it]

Best trial: 36. Best value: 0.135757:  67%|██████▋   | 67/100 [05:30<01:34,  2.86s/it]

Best trial: 36. Best value: 0.135757:  68%|██████▊   | 68/100 [05:30<01:28,  2.76s/it]

Best trial: 36. Best value: 0.135757:  68%|██████▊   | 68/100 [05:32<01:28,  2.76s/it]

Best trial: 36. Best value: 0.135757:  69%|██████▉   | 69/100 [05:32<01:22,  2.67s/it]

Best trial: 36. Best value: 0.135757:  69%|██████▉   | 69/100 [05:36<01:22,  2.67s/it]

Best trial: 36. Best value: 0.135757:  70%|███████   | 70/100 [05:36<01:35,  3.19s/it]

Best trial: 36. Best value: 0.135757:  70%|███████   | 70/100 [05:40<01:35,  3.19s/it]

Best trial: 36. Best value: 0.135757:  71%|███████   | 71/100 [05:40<01:32,  3.20s/it]

Best trial: 71. Best value: 0.135806:  71%|███████   | 71/100 [05:42<01:32,  3.20s/it]

Best trial: 71. Best value: 0.135806:  72%|███████▏  | 72/100 [05:42<01:25,  3.04s/it]

Best trial: 71. Best value: 0.135806:  72%|███████▏  | 72/100 [05:45<01:25,  3.04s/it]

Best trial: 71. Best value: 0.135806:  73%|███████▎  | 73/100 [05:45<01:17,  2.86s/it]

Best trial: 73. Best value: 0.135929:  73%|███████▎  | 73/100 [05:47<01:17,  2.86s/it]

Best trial: 73. Best value: 0.135929:  74%|███████▍  | 74/100 [05:47<01:11,  2.76s/it]

Best trial: 74. Best value: 0.135972:  74%|███████▍  | 74/100 [05:50<01:11,  2.76s/it]

Best trial: 74. Best value: 0.135972:  75%|███████▌  | 75/100 [05:50<01:08,  2.74s/it]

Best trial: 74. Best value: 0.135972:  75%|███████▌  | 75/100 [05:53<01:08,  2.74s/it]

Best trial: 74. Best value: 0.135972:  76%|███████▌  | 76/100 [05:53<01:04,  2.68s/it]

Best trial: 74. Best value: 0.135972:  76%|███████▌  | 76/100 [05:55<01:04,  2.68s/it]

Best trial: 74. Best value: 0.135972:  77%|███████▋  | 77/100 [05:55<01:01,  2.67s/it]

Best trial: 74. Best value: 0.135972:  77%|███████▋  | 77/100 [05:57<01:01,  2.67s/it]

Best trial: 74. Best value: 0.135972:  78%|███████▊  | 78/100 [05:57<00:56,  2.56s/it]

Best trial: 74. Best value: 0.135972:  78%|███████▊  | 78/100 [06:01<00:56,  2.56s/it]

Best trial: 74. Best value: 0.135972:  79%|███████▉  | 79/100 [06:01<01:01,  2.92s/it]

Best trial: 74. Best value: 0.135972:  79%|███████▉  | 79/100 [06:05<01:01,  2.92s/it]

Best trial: 74. Best value: 0.135972:  80%|████████  | 80/100 [06:05<01:00,  3.03s/it]

Best trial: 74. Best value: 0.135972:  80%|████████  | 80/100 [06:07<01:00,  3.03s/it]

Best trial: 74. Best value: 0.135972:  81%|████████  | 81/100 [06:07<00:55,  2.91s/it]

Best trial: 74. Best value: 0.135972:  81%|████████  | 81/100 [06:10<00:55,  2.91s/it]

Best trial: 74. Best value: 0.135972:  82%|████████▏ | 82/100 [06:10<00:51,  2.84s/it]

Best trial: 74. Best value: 0.135972:  82%|████████▏ | 82/100 [06:13<00:51,  2.84s/it]

Best trial: 74. Best value: 0.135972:  83%|████████▎ | 83/100 [06:13<00:50,  2.99s/it]

Best trial: 74. Best value: 0.135972:  83%|████████▎ | 83/100 [06:17<00:50,  2.99s/it]

Best trial: 74. Best value: 0.135972:  84%|████████▍ | 84/100 [06:17<00:49,  3.12s/it]

Best trial: 74. Best value: 0.135972:  84%|████████▍ | 84/100 [06:19<00:49,  3.12s/it]

Best trial: 74. Best value: 0.135972:  85%|████████▌ | 85/100 [06:19<00:45,  3.04s/it]

Best trial: 74. Best value: 0.135972:  85%|████████▌ | 85/100 [06:22<00:45,  3.04s/it]

Best trial: 74. Best value: 0.135972:  86%|████████▌ | 86/100 [06:22<00:41,  2.99s/it]

Best trial: 74. Best value: 0.135972:  86%|████████▌ | 86/100 [06:26<00:41,  2.99s/it]

Best trial: 74. Best value: 0.135972:  87%|████████▋ | 87/100 [06:26<00:39,  3.05s/it]

Best trial: 74. Best value: 0.135972:  87%|████████▋ | 87/100 [06:28<00:39,  3.05s/it]

Best trial: 74. Best value: 0.135972:  88%|████████▊ | 88/100 [06:28<00:35,  2.92s/it]

Best trial: 74. Best value: 0.135972:  88%|████████▊ | 88/100 [06:45<00:35,  2.92s/it]

Best trial: 74. Best value: 0.135972:  89%|████████▉ | 89/100 [06:45<01:19,  7.22s/it]

Best trial: 74. Best value: 0.135972:  89%|████████▉ | 89/100 [06:47<01:19,  7.22s/it]

Best trial: 74. Best value: 0.135972:  90%|█████████ | 90/100 [06:47<00:56,  5.67s/it]

Best trial: 74. Best value: 0.135972:  90%|█████████ | 90/100 [06:49<00:56,  5.67s/it]

Best trial: 74. Best value: 0.135972:  91%|█████████ | 91/100 [06:49<00:41,  4.56s/it]

Best trial: 74. Best value: 0.135972:  91%|█████████ | 91/100 [06:52<00:41,  4.56s/it]

Best trial: 74. Best value: 0.135972:  92%|█████████▏| 92/100 [06:52<00:31,  3.92s/it]

Best trial: 92. Best value: 0.136001:  92%|█████████▏| 92/100 [06:54<00:31,  3.92s/it]

Best trial: 92. Best value: 0.136001:  93%|█████████▎| 93/100 [06:54<00:23,  3.43s/it]

Best trial: 92. Best value: 0.136001:  93%|█████████▎| 93/100 [06:56<00:23,  3.43s/it]

Best trial: 92. Best value: 0.136001:  94%|█████████▍| 94/100 [06:56<00:18,  3.11s/it]

Best trial: 92. Best value: 0.136001:  94%|█████████▍| 94/100 [06:59<00:18,  3.11s/it]

Best trial: 92. Best value: 0.136001:  95%|█████████▌| 95/100 [06:59<00:14,  2.95s/it]

Best trial: 92. Best value: 0.136001:  95%|█████████▌| 95/100 [07:05<00:14,  2.95s/it]

Best trial: 92. Best value: 0.136001:  96%|█████████▌| 96/100 [07:05<00:14,  3.74s/it]

Best trial: 92. Best value: 0.136001:  96%|█████████▌| 96/100 [07:07<00:14,  3.74s/it]

Best trial: 92. Best value: 0.136001:  97%|█████████▋| 97/100 [07:07<00:10,  3.48s/it]

Best trial: 92. Best value: 0.136001:  97%|█████████▋| 97/100 [07:10<00:10,  3.48s/it]

Best trial: 92. Best value: 0.136001:  98%|█████████▊| 98/100 [07:10<00:06,  3.22s/it]

Best trial: 92. Best value: 0.136001:  98%|█████████▊| 98/100 [07:13<00:06,  3.22s/it]

Best trial: 92. Best value: 0.136001:  99%|█████████▉| 99/100 [07:13<00:03,  3.04s/it]

Best trial: 92. Best value: 0.136001:  99%|█████████▉| 99/100 [07:15<00:03,  3.04s/it]

Best trial: 92. Best value: 0.136001: 100%|██████████| 100/100 [07:15<00:00,  2.83s/it]

Best trial: 92. Best value: 0.136001: 100%|██████████| 100/100 [07:15<00:00,  4.36s/it]

Best CV PR-AUC: 0.1360
Best params: {'n_estimators': 399, 'max_depth': 3, 'num_leaves': 231, 'learning_rate': 0.016824662886276414, 'subsample': 0.947873154489602, 'colsample_bytree': 0.9459520098133083, 'min_child_samples': 78, 'scale_pos_weight': 17.75791617892676}

In [9]:
tuned_lgbm = LGBMClassifier(**study_lgbm.best_params, random_state=RANDOM_STATE, verbosity=-1)
tuned_lgbm.fit(X_train, y_train)

tuned_models["LightGBM (tuned)"] = tuned_lgbm
tune_results.append(evaluate_model("LightGBM (tuned)", tuned_lgbm, X_test, y_test, study_lgbm.best_value, stage="tuned"))

2026/07/02 09:34:19 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

LightGBM (tuned): CV=0.1360 | Test AUC=0.6105 | PR-AUC=0.1394 | opt_thr=0.6906 | Precision=0.1358 | Recall=0.7890 | F1=0.2317

## 2.4 Model Comparison
Ranked by **PR-AUC** (threshold-independent, appropriate for this class imbalance).

In [10]:
all_results = pd.DataFrame(results + tune_results).sort_values("PR-AUC", ascending=False)
all_results.reset_index(drop=True)

,Model,CV PR-AUC,CV Std,Test AUC,PR-AUC,Optimal Threshold,Precision (at-risk),Recall (at-risk),F1 (at-risk)
0,Random Forest (tuned),0.1368,-,0.6103,0.1399,0.4708,0.1347,0.7976,0.2305
1,XGBoost (tuned),0.1375,-,0.6107,0.1396,0.5700,0.1352,0.7969,0.2312
2,LightGBM (tuned),0.1360,-,0.6105,0.1394,0.6906,0.1358,0.7890,0.2317
3,LightGBM (baseline),0.1305,0.0018,0.6010,0.1359,0.4508,0.1336,0.7696,0.2277
4,XGBoost (baseline),0.1305,0.0015,0.6001,0.1349,0.4682,0.1342,0.7275,0.2266
5,Logistic Regression,0.1274,0.0022,0.5729,0.1271,0.4886,0.1269,0.7838,0.2184
6,Random Forest (baseline),0.1188,0.001,0.5693,0.1252,0.0663,0.1221,0.7849,0.2113

In [11]:
# Pick overall best model by PR-AUC
best_row   = all_results.iloc[0]
best_name  = best_row['Model']
best_model = tuned_models.get(best_name, fitted_models.get(best_name))
best_threshold = best_row['Optimal Threshold']

print(f"Best model: {best_name}")
print(f"PR-AUC: {best_row['PR-AUC']}")
print(f"Test AUC: {best_row['Test AUC']}")
print(f"Optimal threshold: {best_threshold}")
print(f"Precision (at-risk): {best_row['Precision (at-risk)']}")
print(f"Recall (at-risk): {best_row['Recall (at-risk)']}")
print(f"F1 (at-risk): {best_row['F1 (at-risk)']}")

y_prob_best = best_model.predict_proba(X_test)[:, 1]
y_pred_best = (y_prob_best >= best_threshold).astype(int)
print("\nFull classification report (at optimal threshold):")
print(classification_report(y_test, y_pred_best,
                            target_names=['Returned (0)', 'At-Risk (1)']))

Best model: Random Forest (tuned)
PR-AUC: 0.1399
Test AUC: 0.6103
Optimal threshold: 0.4708
Precision (at-risk): 0.1347
Recall (at-risk): 0.7976
F1 (at-risk): 0.2305

Full classification report (at optimal threshold):
              precision    recall  f1-score   support

Returned (0)       0.94      0.39      0.55     58219
 At-Risk (1)       0.13      0.80      0.23      6937

    accuracy                           0.43     65156
   macro avg       0.54      0.59      0.39     65156
weighted avg       0.86      0.43      0.52     65156

In [12]:
# Save best model + comparison table + its optimal threshold
all_results.to_csv(OUTPUT_DIR / 'model_comparison.csv', index=False)
joblib.dump(best_model, OUTPUT_DIR / 'best_model.pkl')
joblib.dump(best_name,  OUTPUT_DIR / 'best_model_name.pkl')
joblib.dump(float(best_threshold), OUTPUT_DIR / 'optimal_threshold.pkl')

# Save all individual models
for name, m in {**fitted_models, **tuned_models}.items():
    safe = name.lower().replace(' ', '_').replace('(', '').replace(')', '')
    joblib.dump(m, OUTPUT_DIR / f'model_{safe}.pkl')

# Mark the winning run in MLflow so it is easy to find in the UI
best_run = mlflow.search_runs(
    filter_string=f"tags.algorithm = '{best_name}'",
    order_by=['start_time DESC'],
    max_results=1,
)
if not best_run.empty:
    with mlflow.start_run(run_id=best_run.iloc[0]['run_id']):
        mlflow.set_tag('selected_as_best', 'true')
        mlflow.log_artifact(str(OUTPUT_DIR / 'model_comparison.csv'))

print("Saved: best_model.pkl, best_model_name.pkl, optimal_threshold.pkl, model_comparison.csv, all individual models")
print(f'Best model logged to MLflow. Run: mlflow ui --backend-store-uri file:./mlruns  (then open http://127.0.0.1:5000)')
print("Next: run 03_evaluate.ipynb")

Saved: best_model.pkl, best_model_name.pkl, optimal_threshold.pkl, model_comparison.csv, all individual models
Best model logged to MLflow. Run: mlflow ui --backend-store-uri file:./mlruns  (then open http://127.0.0.1:5000)
Next: run 03_evaluate.ipynb