# 2. Model Training & Hyperparameter Tuning
Models compared:
- **Logistic Regression** -- interpretable baseline, no tuning
- **XGBoost** -- tuned with Optuna (100 trials), `scale_pos_weight` tuned as a hyperparameter, optimized for PR-AUC
- **Random Forest** -- `class_weight='balanced_subsample'`, tuned with Optuna (100 trials)

Primary metric: **PR-AUC** (average precision) -- more sensitive to minority-class performance than ROC-AUC under ~9% positive-class imbalance.
Precision/Recall/F1 for each model are reported at that model's own F1-optimal threshold (not the default 0.5), since raw probabilities cluster well below 0.5 for all models here.

> Temporal split: train 2015-2022, test 2023-2025 (no data leakage).

In [1]:
import joblib
import numpy as np
import pandas as pd
import warnings
from datetime import datetime
import optuna
from pathlib import Path
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import (
    roc_auc_score, average_precision_score, precision_recall_curve,
    classification_report, recall_score, precision_score, f1_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import mlflow
import mlflow.sklearn

warnings.filterwarnings('ignore')
optuna.logging.set_verbosity(optuna.logging.WARNING)

mlflow.set_tracking_uri('sqlite:///mlflow.db')
mlflow.set_experiment('njit_dropout_prediction')

OUTPUT_DIR   = Path('outputs')
RANDOM_STATE = 42
CV_FOLDS     = 5
N_TRIALS     = 100

X_train = joblib.load(OUTPUT_DIR / 'X_train.pkl')
X_test  = joblib.load(OUTPUT_DIR / 'X_test.pkl')
y_train = joblib.load(OUTPUT_DIR / 'y_train.pkl')
y_test  = joblib.load(OUTPUT_DIR / 'y_test.pkl')

print(f"Train: {X_train.shape} | Test: {X_test.shape}")
print(f"Train positive rate: {y_train.mean():.4f} | Test: {y_test.mean():.4f}")

C:\Users\prati\Desktop\Project\ARR_NJIT_RD2\ARR_NJIT_RD2\ML_Model\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Train: (124463, 34) | Test: (65156, 34)
Train positive rate: 0.1072 | Test: 0.1065

## 2.1 Shared evaluation helper
Computes PR-AUC (threshold-independent) plus Precision/Recall/F1 at the model's own F1-optimal threshold.

In [2]:
def evaluate_model(name, model, X_test, y_test, cv_metric_value, cv_metric_std='-', stage='baseline'):
    y_prob = model.predict_proba(X_test)[:, 1]
    test_auc  = roc_auc_score(y_test, y_prob)
    pr_auc    = average_precision_score(y_test, y_prob)

    prec, rec, thresholds = precision_recall_curve(y_test, y_prob)
    f1_scores = 2 * prec * rec / (prec + rec + 1e-8)
    best_idx  = f1_scores[:-1].argmax()  # last point has no threshold
    opt_threshold = thresholds[best_idx]

    y_pred_opt = (y_prob >= opt_threshold).astype(int)
    precision  = precision_score(y_test, y_pred_opt, zero_division=0)
    recall     = recall_score(y_test, y_pred_opt, zero_division=0)
    f1         = f1_score(y_test, y_pred_opt, zero_division=0)

    print(f"{name}: CV={cv_metric_value:.4f} | Test AUC={test_auc:.4f} | PR-AUC={pr_auc:.4f} | "
          f"opt_thr={opt_threshold:.4f} | Precision={precision:.4f} | Recall={recall:.4f} | F1={f1:.4f}")

    # Log this model to MLflow: params, metrics, and the fitted model artifact
    with mlflow.start_run(run_name=name):
        raw_params = model.get_params()
        loggable_params = {k: v for k, v in raw_params.items() if isinstance(v, (str, int, float, bool)) or v is None}
        mlflow.log_params(loggable_params)
        mlflow.set_tags({"stage": stage, "algorithm": name, "run_date": datetime.now().strftime("%Y-%m-%d")})
        mlflow.log_metrics({
            "cv_pr_auc": float(cv_metric_value),
            "test_auc": float(test_auc),
            "pr_auc": float(pr_auc),
            "optimal_threshold": float(opt_threshold),
            "precision_at_risk": float(precision),
            "recall_at_risk": float(recall),
            "f1_at_risk": float(f1),
        })
        mlflow.sklearn.log_model(model, name="model", serialization_format="cloudpickle")

    return {
        "Model": name,
        "CV PR-AUC": round(cv_metric_value, 4),
        "CV Std": cv_metric_std if cv_metric_std == '-' else round(cv_metric_std, 4),
        "Test AUC": round(test_auc, 4),
        "PR-AUC": round(pr_auc, 4),
        "Optimal Threshold": round(float(opt_threshold), 4),
        "Precision (at-risk)": round(precision, 4),
        "Recall (at-risk)": round(recall, 4),
        "F1 (at-risk)": round(f1, 4),
    }

## 2.2 Baseline Models (default hyperparameters + class balancing)

In [3]:
cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
pos_weight = (1 - y_train.mean()) / y_train.mean()

baseline_models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(
            class_weight="balanced", max_iter=2000,
            solver="saga", random_state=RANDOM_STATE,
        )),
    ]),
}

results = []
fitted_models = {}

for name, model in baseline_models.items():
    cv_scores = cross_val_score(
        model, X_train, y_train, cv=cv, scoring="average_precision", n_jobs=-1
    )
    model.fit(X_train, y_train)
    results.append(evaluate_model(name, model, X_test, y_test, cv_scores.mean(), cv_scores.std(), stage="baseline"))
    fitted_models[name] = model

pd.DataFrame(results)

Logistic Regression: CV=0.1270 | Test AUC=0.5732 | PR-AUC=0.1273 | opt_thr=0.4897 | Precision=0.1267 | Recall=0.7789 | F1=0.2180

2026/07/04 22:04:01 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

,Model,CV PR-AUC,CV Std,Test AUC,PR-AUC,Optimal Threshold,Precision (at-risk),Recall (at-risk),F1 (at-risk)
0,Logistic Regression,0.127,0.0021,0.5732,0.1273,0.4897,0.1267,0.7789,0.218

## 2.3 Hyperparameter Tuning with Optuna
Logistic Regression is kept as an interpretable baseline with no tuning. XGBoost and Random Forest are each tuned with 100 Bayesian trials, optimizing **PR-AUC** (`average_precision`) via 3-fold CV. `scale_pos_weight` is tuned as a hyperparameter (not fixed) for XGBoost.

### 2.3.1 XGBoost

In [4]:
def objective_xgb(trial):
    params = {
        "n_estimators":     trial.suggest_int("n_estimators", 100, 600),
        "max_depth":        trial.suggest_int("max_depth", 3, 10),
        "learning_rate":    trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "subsample":        trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma":            trial.suggest_float("gamma", 0.0, 5.0),
        "scale_pos_weight": trial.suggest_float("scale_pos_weight", 5.0, 20.0),
        "eval_metric":      "aucpr",
        "random_state":     RANDOM_STATE,
        "verbosity":        0,
    }
    model = XGBClassifier(**params)
    scores = cross_val_score(
        model, X_train, y_train,
        cv=StratifiedKFold(3, shuffle=True, random_state=RANDOM_STATE),
        scoring="average_precision", n_jobs=-1,
    )
    return scores.mean()

print("Tuning XGBoost with Optuna (100 trials, optimizing PR-AUC) ...")
study_xgb = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study_xgb.optimize(objective_xgb, n_trials=N_TRIALS, show_progress_bar=True)
print(f"Best CV PR-AUC: {study_xgb.best_value:.4f}")
print(f"Best params: {study_xgb.best_params}")

Tuning XGBoost with Optuna (100 trials, optimizing PR-AUC) ...

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.11674:   0%|          | 0/100 [00:15<?, ?it/s]

Best trial: 0. Best value: 0.11674:   1%|          | 1/100 [00:15<25:42, 15.58s/it]

Best trial: 1. Best value: 0.133884:   1%|          | 1/100 [00:31<25:42, 15.58s/it]

Best trial: 1. Best value: 0.133884:   2%|▏         | 2/100 [00:31<25:19, 15.50s/it]

Best trial: 1. Best value: 0.133884:   2%|▏         | 2/100 [00:42<25:19, 15.50s/it]

Best trial: 1. Best value: 0.133884:   3%|▎         | 3/100 [00:42<21:43, 13.44s/it]

Best trial: 1. Best value: 0.133884:   3%|▎         | 3/100 [00:51<21:43, 13.44s/it]

Best trial: 1. Best value: 0.133884:   4%|▍         | 4/100 [00:51<19:09, 11.97s/it]

Best trial: 1. Best value: 0.133884:   4%|▍         | 4/100 [00:55<19:09, 11.97s/it]

Best trial: 1. Best value: 0.133884:   5%|▌         | 5/100 [00:55<14:14,  8.99s/it]

Best trial: 5. Best value: 0.136812:   5%|▌         | 5/100 [01:01<14:14,  8.99s/it]

Best trial: 5. Best value: 0.136812:   6%|▌         | 6/100 [01:01<12:20,  7.88s/it]

Best trial: 5. Best value: 0.136812:   6%|▌         | 6/100 [01:09<12:20,  7.88s/it]

Best trial: 5. Best value: 0.136812:   7%|▋         | 7/100 [01:09<12:21,  7.98s/it]

Best trial: 5. Best value: 0.136812:   7%|▋         | 7/100 [01:13<12:21,  7.98s/it]

Best trial: 5. Best value: 0.136812:   8%|▊         | 8/100 [01:13<10:18,  6.72s/it]

Best trial: 5. Best value: 0.136812:   8%|▊         | 8/100 [01:20<10:18,  6.72s/it]

Best trial: 5. Best value: 0.136812:   9%|▉         | 9/100 [01:20<10:32,  6.95s/it]

Best trial: 5. Best value: 0.136812:   9%|▉         | 9/100 [01:24<10:32,  6.95s/it]

Best trial: 5. Best value: 0.136812:  10%|█         | 10/100 [01:24<09:02,  6.03s/it]

Best trial: 5. Best value: 0.136812:  10%|█         | 10/100 [01:35<09:02,  6.03s/it]

Best trial: 5. Best value: 0.136812:  11%|█         | 11/100 [01:35<10:53,  7.34s/it]

Best trial: 5. Best value: 0.136812:  11%|█         | 11/100 [01:39<10:53,  7.34s/it]

Best trial: 5. Best value: 0.136812:  12%|█▏        | 12/100 [01:39<09:38,  6.57s/it]

Best trial: 5. Best value: 0.136812:  12%|█▏        | 12/100 [01:44<09:38,  6.57s/it]

Best trial: 5. Best value: 0.136812:  13%|█▎        | 13/100 [01:44<08:37,  5.95s/it]

Best trial: 5. Best value: 0.136812:  13%|█▎        | 13/100 [01:48<08:37,  5.95s/it]

Best trial: 5. Best value: 0.136812:  14%|█▍        | 14/100 [01:48<07:31,  5.26s/it]

Best trial: 5. Best value: 0.136812:  14%|█▍        | 14/100 [01:58<07:31,  5.26s/it]

Best trial: 5. Best value: 0.136812:  15%|█▌        | 15/100 [01:58<09:45,  6.89s/it]

Best trial: 5. Best value: 0.136812:  15%|█▌        | 15/100 [02:04<09:45,  6.89s/it]

Best trial: 5. Best value: 0.136812:  16%|█▌        | 16/100 [02:04<09:01,  6.45s/it]

Best trial: 5. Best value: 0.136812:  16%|█▌        | 16/100 [02:10<09:01,  6.45s/it]

Best trial: 5. Best value: 0.136812:  17%|█▋        | 17/100 [02:10<08:52,  6.41s/it]

Best trial: 5. Best value: 0.136812:  17%|█▋        | 17/100 [02:18<08:52,  6.41s/it]

Best trial: 5. Best value: 0.136812:  18%|█▊        | 18/100 [02:18<09:20,  6.84s/it]

Best trial: 5. Best value: 0.136812:  18%|█▊        | 18/100 [02:25<09:20,  6.84s/it]

Best trial: 5. Best value: 0.136812:  19%|█▉        | 19/100 [02:25<09:09,  6.78s/it]

Best trial: 5. Best value: 0.136812:  19%|█▉        | 19/100 [02:33<09:09,  6.78s/it]

Best trial: 5. Best value: 0.136812:  20%|██        | 20/100 [02:33<09:46,  7.33s/it]

Best trial: 5. Best value: 0.136812:  20%|██        | 20/100 [02:39<09:46,  7.33s/it]

Best trial: 5. Best value: 0.136812:  21%|██        | 21/100 [02:39<09:07,  6.93s/it]

Best trial: 5. Best value: 0.136812:  21%|██        | 21/100 [02:45<09:07,  6.93s/it]

Best trial: 5. Best value: 0.136812:  22%|██▏       | 22/100 [02:45<08:36,  6.62s/it]

Best trial: 5. Best value: 0.136812:  22%|██▏       | 22/100 [02:49<08:36,  6.62s/it]

Best trial: 5. Best value: 0.136812:  23%|██▎       | 23/100 [02:49<07:40,  5.97s/it]

Best trial: 5. Best value: 0.136812:  23%|██▎       | 23/100 [02:53<07:40,  5.97s/it]

Best trial: 5. Best value: 0.136812:  24%|██▍       | 24/100 [02:53<06:39,  5.25s/it]

Best trial: 5. Best value: 0.136812:  24%|██▍       | 24/100 [02:57<06:39,  5.25s/it]

Best trial: 5. Best value: 0.136812:  25%|██▌       | 25/100 [02:57<06:14,  4.99s/it]

Best trial: 5. Best value: 0.136812:  25%|██▌       | 25/100 [03:01<06:14,  4.99s/it]

Best trial: 5. Best value: 0.136812:  26%|██▌       | 26/100 [03:01<05:38,  4.58s/it]

Best trial: 5. Best value: 0.136812:  26%|██▌       | 26/100 [03:06<05:38,  4.58s/it]

Best trial: 5. Best value: 0.136812:  27%|██▋       | 27/100 [03:06<05:37,  4.62s/it]

Best trial: 5. Best value: 0.136812:  27%|██▋       | 27/100 [03:10<05:37,  4.62s/it]

Best trial: 5. Best value: 0.136812:  28%|██▊       | 28/100 [03:10<05:27,  4.55s/it]

Best trial: 5. Best value: 0.136812:  28%|██▊       | 28/100 [03:13<05:27,  4.55s/it]

Best trial: 5. Best value: 0.136812:  29%|██▉       | 29/100 [03:13<04:49,  4.08s/it]

Best trial: 5. Best value: 0.136812:  29%|██▉       | 29/100 [03:20<04:49,  4.08s/it]

Best trial: 5. Best value: 0.136812:  30%|███       | 30/100 [03:20<05:42,  4.90s/it]

Best trial: 5. Best value: 0.136812:  30%|███       | 30/100 [03:23<05:42,  4.90s/it]

Best trial: 5. Best value: 0.136812:  31%|███       | 31/100 [03:23<04:59,  4.34s/it]

Best trial: 5. Best value: 0.136812:  31%|███       | 31/100 [03:29<04:59,  4.34s/it]

Best trial: 5. Best value: 0.136812:  32%|███▏      | 32/100 [03:29<05:37,  4.97s/it]

Best trial: 5. Best value: 0.136812:  32%|███▏      | 32/100 [03:37<05:37,  4.97s/it]

Best trial: 5. Best value: 0.136812:  33%|███▎      | 33/100 [03:37<06:17,  5.63s/it]

Best trial: 5. Best value: 0.136812:  33%|███▎      | 33/100 [03:44<06:17,  5.63s/it]

Best trial: 5. Best value: 0.136812:  34%|███▍      | 34/100 [03:44<06:39,  6.06s/it]

Best trial: 5. Best value: 0.136812:  34%|███▍      | 34/100 [03:48<06:39,  6.06s/it]

Best trial: 5. Best value: 0.136812:  35%|███▌      | 35/100 [03:48<05:54,  5.46s/it]

Best trial: 5. Best value: 0.136812:  35%|███▌      | 35/100 [03:55<05:54,  5.46s/it]

Best trial: 5. Best value: 0.136812:  36%|███▌      | 36/100 [03:55<06:15,  5.87s/it]

Best trial: 5. Best value: 0.136812:  36%|███▌      | 36/100 [04:00<06:15,  5.87s/it]

Best trial: 5. Best value: 0.136812:  37%|███▋      | 37/100 [04:00<06:09,  5.87s/it]

Best trial: 5. Best value: 0.136812:  37%|███▋      | 37/100 [04:04<06:09,  5.87s/it]

Best trial: 5. Best value: 0.136812:  38%|███▊      | 38/100 [04:04<05:28,  5.30s/it]

Best trial: 5. Best value: 0.136812:  38%|███▊      | 38/100 [04:10<05:28,  5.30s/it]

Best trial: 5. Best value: 0.136812:  39%|███▉      | 39/100 [04:10<05:20,  5.25s/it]

Best trial: 5. Best value: 0.136812:  39%|███▉      | 39/100 [04:20<05:20,  5.25s/it]

Best trial: 5. Best value: 0.136812:  40%|████      | 40/100 [04:20<06:50,  6.85s/it]

Best trial: 5. Best value: 0.136812:  40%|████      | 40/100 [04:24<06:50,  6.85s/it]

Best trial: 5. Best value: 0.136812:  41%|████      | 41/100 [04:24<06:00,  6.12s/it]

Best trial: 5. Best value: 0.136812:  41%|████      | 41/100 [04:29<06:00,  6.12s/it]

Best trial: 5. Best value: 0.136812:  42%|████▏     | 42/100 [04:29<05:31,  5.71s/it]

Best trial: 5. Best value: 0.136812:  42%|████▏     | 42/100 [04:34<05:31,  5.71s/it]

Best trial: 5. Best value: 0.136812:  43%|████▎     | 43/100 [04:34<05:03,  5.32s/it]

Best trial: 5. Best value: 0.136812:  43%|████▎     | 43/100 [04:37<05:03,  5.32s/it]

Best trial: 5. Best value: 0.136812:  44%|████▍     | 44/100 [04:37<04:27,  4.77s/it]

Best trial: 5. Best value: 0.136812:  44%|████▍     | 44/100 [04:41<04:27,  4.77s/it]

Best trial: 5. Best value: 0.136812:  45%|████▌     | 45/100 [04:41<04:07,  4.49s/it]

Best trial: 5. Best value: 0.136812:  45%|████▌     | 45/100 [04:47<04:07,  4.49s/it]

Best trial: 5. Best value: 0.136812:  46%|████▌     | 46/100 [04:47<04:20,  4.83s/it]

Best trial: 5. Best value: 0.136812:  46%|████▌     | 46/100 [04:50<04:20,  4.83s/it]

Best trial: 5. Best value: 0.136812:  47%|████▋     | 47/100 [04:50<03:51,  4.37s/it]

Best trial: 5. Best value: 0.136812:  47%|████▋     | 47/100 [04:53<03:51,  4.37s/it]

Best trial: 5. Best value: 0.136812:  48%|████▊     | 48/100 [04:53<03:32,  4.09s/it]

Best trial: 5. Best value: 0.136812:  48%|████▊     | 48/100 [04:58<03:32,  4.09s/it]

Best trial: 5. Best value: 0.136812:  49%|████▉     | 49/100 [04:58<03:44,  4.40s/it]

Best trial: 5. Best value: 0.136812:  49%|████▉     | 49/100 [05:02<03:44,  4.40s/it]

Best trial: 5. Best value: 0.136812:  50%|█████     | 50/100 [05:02<03:23,  4.06s/it]

Best trial: 5. Best value: 0.136812:  50%|█████     | 50/100 [05:06<03:23,  4.06s/it]

Best trial: 5. Best value: 0.136812:  51%|█████     | 51/100 [05:06<03:22,  4.14s/it]

Best trial: 5. Best value: 0.136812:  51%|█████     | 51/100 [05:09<03:22,  4.14s/it]

Best trial: 5. Best value: 0.136812:  52%|█████▏    | 52/100 [05:09<03:03,  3.82s/it]

Best trial: 5. Best value: 0.136812:  52%|█████▏    | 52/100 [05:20<03:03,  3.82s/it]

Best trial: 5. Best value: 0.136812:  53%|█████▎    | 53/100 [05:20<04:38,  5.93s/it]

Best trial: 5. Best value: 0.136812:  53%|█████▎    | 53/100 [05:24<04:38,  5.93s/it]

Best trial: 5. Best value: 0.136812:  54%|█████▍    | 54/100 [05:24<04:03,  5.29s/it]

Best trial: 5. Best value: 0.136812:  54%|█████▍    | 54/100 [05:28<04:03,  5.29s/it]

Best trial: 5. Best value: 0.136812:  55%|█████▌    | 55/100 [05:28<03:49,  5.09s/it]

Best trial: 5. Best value: 0.136812:  55%|█████▌    | 55/100 [05:35<03:49,  5.09s/it]

Best trial: 5. Best value: 0.136812:  56%|█████▌    | 56/100 [05:35<03:58,  5.41s/it]

Best trial: 5. Best value: 0.136812:  56%|█████▌    | 56/100 [05:41<03:58,  5.41s/it]

Best trial: 5. Best value: 0.136812:  57%|█████▋    | 57/100 [05:41<04:00,  5.60s/it]

Best trial: 5. Best value: 0.136812:  57%|█████▋    | 57/100 [05:48<04:00,  5.60s/it]

Best trial: 5. Best value: 0.136812:  58%|█████▊    | 58/100 [05:48<04:12,  6.00s/it]

Best trial: 5. Best value: 0.136812:  58%|█████▊    | 58/100 [05:55<04:12,  6.00s/it]

Best trial: 5. Best value: 0.136812:  59%|█████▉    | 59/100 [05:55<04:26,  6.50s/it]

Best trial: 5. Best value: 0.136812:  59%|█████▉    | 59/100 [06:00<04:26,  6.50s/it]

Best trial: 5. Best value: 0.136812:  60%|██████    | 60/100 [06:00<04:01,  6.03s/it]

Best trial: 5. Best value: 0.136812:  60%|██████    | 60/100 [06:05<04:01,  6.03s/it]

Best trial: 5. Best value: 0.136812:  61%|██████    | 61/100 [06:05<03:36,  5.56s/it]

Best trial: 5. Best value: 0.136812:  61%|██████    | 61/100 [06:09<03:36,  5.56s/it]

Best trial: 5. Best value: 0.136812:  62%|██████▏   | 62/100 [06:09<03:20,  5.28s/it]

Best trial: 62. Best value: 0.136831:  62%|██████▏   | 62/100 [06:14<03:20,  5.28s/it]

Best trial: 62. Best value: 0.136831:  63%|██████▎   | 63/100 [06:14<03:12,  5.21s/it]

Best trial: 62. Best value: 0.136831:  63%|██████▎   | 63/100 [06:20<03:12,  5.21s/it]

Best trial: 62. Best value: 0.136831:  64%|██████▍   | 64/100 [06:20<03:10,  5.28s/it]

Best trial: 62. Best value: 0.136831:  64%|██████▍   | 64/100 [06:25<03:10,  5.28s/it]

Best trial: 62. Best value: 0.136831:  65%|██████▌   | 65/100 [06:25<03:02,  5.23s/it]

Best trial: 62. Best value: 0.136831:  65%|██████▌   | 65/100 [06:31<03:02,  5.23s/it]

Best trial: 62. Best value: 0.136831:  66%|██████▌   | 66/100 [06:31<03:09,  5.57s/it]

Best trial: 62. Best value: 0.136831:  66%|██████▌   | 66/100 [06:36<03:09,  5.57s/it]

Best trial: 62. Best value: 0.136831:  67%|██████▋   | 67/100 [06:36<03:00,  5.46s/it]

Best trial: 62. Best value: 0.136831:  67%|██████▋   | 67/100 [06:40<03:00,  5.46s/it]

Best trial: 62. Best value: 0.136831:  68%|██████▊   | 68/100 [06:40<02:36,  4.88s/it]

Best trial: 62. Best value: 0.136831:  68%|██████▊   | 68/100 [06:46<02:36,  4.88s/it]

Best trial: 62. Best value: 0.136831:  69%|██████▉   | 69/100 [06:46<02:40,  5.17s/it]

Best trial: 62. Best value: 0.136831:  69%|██████▉   | 69/100 [06:50<02:40,  5.17s/it]

Best trial: 62. Best value: 0.136831:  70%|███████   | 70/100 [06:50<02:23,  4.79s/it]

Best trial: 62. Best value: 0.136831:  70%|███████   | 70/100 [06:55<02:23,  4.79s/it]

Best trial: 62. Best value: 0.136831:  71%|███████   | 71/100 [06:55<02:21,  4.86s/it]

Best trial: 62. Best value: 0.136831:  71%|███████   | 71/100 [07:01<02:21,  4.86s/it]

Best trial: 62. Best value: 0.136831:  72%|███████▏  | 72/100 [07:01<02:24,  5.18s/it]

Best trial: 62. Best value: 0.136831:  72%|███████▏  | 72/100 [07:06<02:24,  5.18s/it]

Best trial: 62. Best value: 0.136831:  73%|███████▎  | 73/100 [07:06<02:24,  5.35s/it]

Best trial: 62. Best value: 0.136831:  73%|███████▎  | 73/100 [07:12<02:24,  5.35s/it]

Best trial: 62. Best value: 0.136831:  74%|███████▍  | 74/100 [07:12<02:22,  5.49s/it]

Best trial: 62. Best value: 0.136831:  74%|███████▍  | 74/100 [07:19<02:22,  5.49s/it]

Best trial: 62. Best value: 0.136831:  75%|███████▌  | 75/100 [07:19<02:26,  5.85s/it]

Best trial: 62. Best value: 0.136831:  75%|███████▌  | 75/100 [07:26<02:26,  5.85s/it]

Best trial: 62. Best value: 0.136831:  76%|███████▌  | 76/100 [07:26<02:26,  6.10s/it]

Best trial: 62. Best value: 0.136831:  76%|███████▌  | 76/100 [07:32<02:26,  6.10s/it]

Best trial: 62. Best value: 0.136831:  77%|███████▋  | 77/100 [07:32<02:25,  6.31s/it]

Best trial: 62. Best value: 0.136831:  77%|███████▋  | 77/100 [07:39<02:25,  6.31s/it]

Best trial: 62. Best value: 0.136831:  78%|███████▊  | 78/100 [07:39<02:19,  6.36s/it]

Best trial: 62. Best value: 0.136831:  78%|███████▊  | 78/100 [07:44<02:19,  6.36s/it]

Best trial: 62. Best value: 0.136831:  79%|███████▉  | 79/100 [07:44<02:03,  5.89s/it]

Best trial: 62. Best value: 0.136831:  79%|███████▉  | 79/100 [07:48<02:03,  5.89s/it]

Best trial: 62. Best value: 0.136831:  80%|████████  | 80/100 [07:48<01:46,  5.30s/it]

Best trial: 62. Best value: 0.136831:  80%|████████  | 80/100 [08:00<01:46,  5.30s/it]

Best trial: 62. Best value: 0.136831:  81%|████████  | 81/100 [08:00<02:19,  7.35s/it]

Best trial: 62. Best value: 0.136831:  81%|████████  | 81/100 [08:06<02:19,  7.35s/it]

Best trial: 62. Best value: 0.136831:  82%|████████▏ | 82/100 [08:06<02:08,  7.13s/it]

Best trial: 62. Best value: 0.136831:  82%|████████▏ | 82/100 [08:12<02:08,  7.13s/it]

Best trial: 62. Best value: 0.136831:  83%|████████▎ | 83/100 [08:12<01:55,  6.77s/it]

Best trial: 62. Best value: 0.136831:  83%|████████▎ | 83/100 [08:20<01:55,  6.77s/it]

Best trial: 62. Best value: 0.136831:  84%|████████▍ | 84/100 [08:20<01:52,  7.03s/it]

Best trial: 62. Best value: 0.136831:  84%|████████▍ | 84/100 [08:29<01:52,  7.03s/it]

Best trial: 62. Best value: 0.136831:  85%|████████▌ | 85/100 [08:29<01:56,  7.75s/it]

Best trial: 62. Best value: 0.136831:  85%|████████▌ | 85/100 [08:37<01:56,  7.75s/it]

Best trial: 62. Best value: 0.136831:  86%|████████▌ | 86/100 [08:37<01:48,  7.76s/it]

Best trial: 62. Best value: 0.136831:  86%|████████▌ | 86/100 [08:41<01:48,  7.76s/it]

Best trial: 62. Best value: 0.136831:  87%|████████▋ | 87/100 [08:41<01:24,  6.51s/it]

Best trial: 62. Best value: 0.136831:  87%|████████▋ | 87/100 [08:46<01:24,  6.51s/it]

Best trial: 62. Best value: 0.136831:  88%|████████▊ | 88/100 [08:46<01:12,  6.02s/it]

Best trial: 62. Best value: 0.136831:  88%|████████▊ | 88/100 [08:52<01:12,  6.02s/it]

Best trial: 62. Best value: 0.136831:  89%|████████▉ | 89/100 [08:52<01:08,  6.22s/it]

Best trial: 62. Best value: 0.136831:  89%|████████▉ | 89/100 [08:59<01:08,  6.22s/it]

Best trial: 62. Best value: 0.136831:  90%|█████████ | 90/100 [08:59<01:02,  6.27s/it]

Best trial: 62. Best value: 0.136831:  90%|█████████ | 90/100 [09:04<01:02,  6.27s/it]

Best trial: 62. Best value: 0.136831:  91%|█████████ | 91/100 [09:04<00:54,  6.01s/it]

Best trial: 62. Best value: 0.136831:  91%|█████████ | 91/100 [09:09<00:54,  6.01s/it]

Best trial: 62. Best value: 0.136831:  92%|█████████▏| 92/100 [09:09<00:45,  5.69s/it]

Best trial: 62. Best value: 0.136831:  92%|█████████▏| 92/100 [09:14<00:45,  5.69s/it]

Best trial: 62. Best value: 0.136831:  93%|█████████▎| 93/100 [09:14<00:39,  5.60s/it]

Best trial: 62. Best value: 0.136831:  93%|█████████▎| 93/100 [09:19<00:39,  5.60s/it]

Best trial: 62. Best value: 0.136831:  94%|█████████▍| 94/100 [09:19<00:31,  5.33s/it]

Best trial: 62. Best value: 0.136831:  94%|█████████▍| 94/100 [09:25<00:31,  5.33s/it]

Best trial: 62. Best value: 0.136831:  95%|█████████▌| 95/100 [09:25<00:27,  5.56s/it]

Best trial: 62. Best value: 0.136831:  95%|█████████▌| 95/100 [09:32<00:27,  5.56s/it]

Best trial: 62. Best value: 0.136831:  96%|█████████▌| 96/100 [09:32<00:23,  5.81s/it]

Best trial: 96. Best value: 0.136872:  96%|█████████▌| 96/100 [09:37<00:23,  5.81s/it]

Best trial: 96. Best value: 0.136872:  97%|█████████▋| 97/100 [09:37<00:17,  5.75s/it]

Best trial: 96. Best value: 0.136872:  97%|█████████▋| 97/100 [09:43<00:17,  5.75s/it]

Best trial: 96. Best value: 0.136872:  98%|█████████▊| 98/100 [09:43<00:11,  5.67s/it]

Best trial: 96. Best value: 0.136872:  98%|█████████▊| 98/100 [09:48<00:11,  5.67s/it]

Best trial: 96. Best value: 0.136872:  99%|█████████▉| 99/100 [09:48<00:05,  5.52s/it]

Best trial: 96. Best value: 0.136872:  99%|█████████▉| 99/100 [09:53<00:05,  5.52s/it]

Best trial: 96. Best value: 0.136872: 100%|██████████| 100/100 [09:53<00:00,  5.45s/it]

Best trial: 96. Best value: 0.136872: 100%|██████████| 100/100 [09:53<00:00,  5.94s/it]

Best CV PR-AUC: 0.1369
Best params: {'n_estimators': 175, 'max_depth': 6, 'learning_rate': 0.010809646327535477, 'subsample': 0.94008823618446, 'colsample_bytree': 0.6876339909025658, 'min_child_weight': 7, 'gamma': 3.1645615907198157, 'scale_pos_weight': 13.026108756182351}

In [5]:
tuned_xgb = XGBClassifier(**study_xgb.best_params, eval_metric="aucpr", random_state=RANDOM_STATE, verbosity=0)
tuned_xgb.fit(X_train, y_train)

tuned_models = {}
tune_results = []

tuned_models["XGBoost (tuned)"] = tuned_xgb
tune_results.append(evaluate_model("XGBoost (tuned)", tuned_xgb, X_test, y_test, study_xgb.best_value, stage="tuned"))

XGBoost (tuned): CV=0.1369 | Test AUC=0.6097 | PR-AUC=0.1391 | opt_thr=0.5969 | Precision=0.1351 | Recall=0.7976 | F1=0.2310

2026/07/04 22:14:08 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

### 2.3.2 Random Forest

In [6]:
def objective_rf(trial):
    params = {
        "n_estimators":      trial.suggest_int("n_estimators", 100, 600),
        "max_depth":         trial.suggest_int("max_depth", 4, 30),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 30),
        "min_samples_leaf":  trial.suggest_int("min_samples_leaf", 1, 30),
        "max_features":      trial.suggest_float("max_features", 0.3, 1.0),
        "class_weight":      "balanced_subsample",
        "random_state":      RANDOM_STATE,
        "n_jobs":            -1,
    }
    model = RandomForestClassifier(**params)
    scores = cross_val_score(
        model, X_train, y_train,
        cv=StratifiedKFold(3, shuffle=True, random_state=RANDOM_STATE),
        scoring="average_precision", n_jobs=-1,
    )
    return scores.mean()

print("Tuning Random Forest with Optuna (100 trials, optimizing PR-AUC) ...")
study_rf = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study_rf.optimize(objective_rf, n_trials=N_TRIALS, show_progress_bar=True)
print(f"Best CV PR-AUC: {study_rf.best_value:.4f}")
print(f"Best params: {study_rf.best_params}")

Tuning Random Forest with Optuna (100 trials, optimizing PR-AUC) ...

  0%|          | 0/100 [00:00<?, ?it/s]

Best trial: 0. Best value: 0.128476:   0%|          | 0/100 [00:46<?, ?it/s]

Best trial: 0. Best value: 0.128476:   1%|          | 1/100 [00:46<1:17:32, 46.99s/it]

Best trial: 1. Best value: 0.135573:   1%|          | 1/100 [01:06<1:17:32, 46.99s/it]

Best trial: 1. Best value: 0.135573:   2%|▏         | 2/100 [01:06<50:31, 30.94s/it]

Best trial: 1. Best value: 0.135573:   2%|▏         | 2/100 [01:28<50:31, 30.94s/it]

Best trial: 1. Best value: 0.135573:   3%|▎         | 3/100 [01:28<43:05, 26.65s/it]

Best trial: 1. Best value: 0.135573:   3%|▎         | 3/100 [01:55<43:05, 26.65s/it]

Best trial: 1. Best value: 0.135573:   4%|▍         | 4/100 [01:55<43:05, 26.93s/it]

Best trial: 1. Best value: 0.135573:   4%|▍         | 4/100 [02:37<43:05, 26.93s/it]

Best trial: 1. Best value: 0.135573:   5%|▌         | 5/100 [02:37<51:27, 32.50s/it]

Best trial: 1. Best value: 0.135573:   5%|▌         | 5/100 [03:17<51:27, 32.50s/it]

Best trial: 1. Best value: 0.135573:   6%|▌         | 6/100 [03:17<54:53, 35.03s/it]

Best trial: 6. Best value: 0.135931:   6%|▌         | 6/100 [04:27<54:53, 35.03s/it]

Best trial: 6. Best value: 0.135931:   7%|▋         | 7/100 [04:27<1:11:57, 46.43s/it]

Best trial: 6. Best value: 0.135931:   7%|▋         | 7/100 [05:43<1:11:57, 46.43s/it]

Best trial: 6. Best value: 0.135931:   8%|▊         | 8/100 [05:43<1:25:40, 55.87s/it]

Best trial: 6. Best value: 0.135931:   8%|▊         | 8/100 [06:09<1:25:40, 55.87s/it]

Best trial: 6. Best value: 0.135931:   9%|▉         | 9/100 [06:09<1:10:31, 46.50s/it]

Best trial: 6. Best value: 0.135931:   9%|▉         | 9/100 [06:59<1:10:31, 46.50s/it]

Best trial: 6. Best value: 0.135931:  10%|█         | 10/100 [06:59<1:11:13, 47.48s/it]

Best trial: 6. Best value: 0.135931:  10%|█         | 10/100 [10:33<1:11:13, 47.48s/it]

Best trial: 6. Best value: 0.135931:  11%|█         | 11/100 [10:33<2:25:56, 98.39s/it]

Best trial: 6. Best value: 0.135931:  11%|█         | 11/100 [10:54<2:25:56, 98.39s/it]

Best trial: 6. Best value: 0.135931:  12%|█▏        | 12/100 [10:54<1:50:00, 75.01s/it]

Best trial: 6. Best value: 0.135931:  12%|█▏        | 12/100 [11:14<1:50:00, 75.01s/it]

Best trial: 6. Best value: 0.135931:  13%|█▎        | 13/100 [11:14<1:24:31, 58.29s/it]

Best trial: 13. Best value: 0.136103:  13%|█▎        | 13/100 [11:52<1:24:31, 58.29s/it]

Best trial: 13. Best value: 0.136103:  14%|█▍        | 14/100 [11:52<1:14:41, 52.11s/it]

Best trial: 13. Best value: 0.136103:  14%|█▍        | 14/100 [13:04<1:14:41, 52.11s/it]

Best trial: 13. Best value: 0.136103:  15%|█▌        | 15/100 [13:04<1:22:19, 58.11s/it]

Best trial: 13. Best value: 0.136103:  15%|█▌        | 15/100 [14:00<1:22:19, 58.11s/it]

Best trial: 13. Best value: 0.136103:  16%|█▌        | 16/100 [14:00<1:20:38, 57.60s/it]

Best trial: 13. Best value: 0.136103:  16%|█▌        | 16/100 [15:15<1:20:38, 57.60s/it]

Best trial: 13. Best value: 0.136103:  17%|█▋        | 17/100 [15:15<1:26:50, 62.78s/it]

Best trial: 17. Best value: 0.136135:  17%|█▋        | 17/100 [16:41<1:26:50, 62.78s/it]

Best trial: 17. Best value: 0.136135:  18%|█▊        | 18/100 [16:41<1:35:16, 69.72s/it]

Best trial: 17. Best value: 0.136135:  18%|█▊        | 18/100 [19:10<1:35:16, 69.72s/it]

Best trial: 17. Best value: 0.136135:  19%|█▉        | 19/100 [19:10<2:06:10, 93.46s/it]

Best trial: 17. Best value: 0.136135:  19%|█▉        | 19/100 [20:44<2:06:10, 93.46s/it]

Best trial: 17. Best value: 0.136135:  20%|██        | 20/100 [20:44<2:04:40, 93.51s/it]

Best trial: 17. Best value: 0.136135:  20%|██        | 20/100 [21:43<2:04:40, 93.51s/it]

Best trial: 17. Best value: 0.136135:  21%|██        | 21/100 [21:43<1:49:50, 83.42s/it]

Best trial: 17. Best value: 0.136135:  21%|██        | 21/100 [22:53<1:49:50, 83.42s/it]

Best trial: 17. Best value: 0.136135:  22%|██▏       | 22/100 [22:53<1:43:14, 79.42s/it]

Best trial: 17. Best value: 0.136135:  22%|██▏       | 22/100 [23:59<1:43:14, 79.42s/it]

Best trial: 17. Best value: 0.136135:  23%|██▎       | 23/100 [23:59<1:36:36, 75.28s/it]

Best trial: 17. Best value: 0.136135:  23%|██▎       | 23/100 [25:01<1:36:36, 75.28s/it]

Best trial: 17. Best value: 0.136135:  24%|██▍       | 24/100 [25:01<1:30:16, 71.27s/it]

Best trial: 17. Best value: 0.136135:  24%|██▍       | 24/100 [25:57<1:30:16, 71.27s/it]

Best trial: 17. Best value: 0.136135:  25%|██▌       | 25/100 [25:57<1:23:09, 66.53s/it]

Best trial: 17. Best value: 0.136135:  25%|██▌       | 25/100 [26:53<1:23:09, 66.53s/it]

Best trial: 17. Best value: 0.136135:  26%|██▌       | 26/100 [26:53<1:18:15, 63.45s/it]

Best trial: 17. Best value: 0.136135:  26%|██▌       | 26/100 [28:42<1:18:15, 63.45s/it]

Best trial: 17. Best value: 0.136135:  27%|██▋       | 27/100 [28:42<1:33:57, 77.23s/it]

Best trial: 17. Best value: 0.136135:  27%|██▋       | 27/100 [29:54<1:33:57, 77.23s/it]

Best trial: 17. Best value: 0.136135:  28%|██▊       | 28/100 [29:54<1:30:42, 75.58s/it]

Best trial: 28. Best value: 0.136138:  28%|██▊       | 28/100 [30:42<1:30:42, 75.58s/it]

Best trial: 28. Best value: 0.136138:  29%|██▉       | 29/100 [30:42<1:19:30, 67.19s/it]

Best trial: 28. Best value: 0.136138:  29%|██▉       | 29/100 [32:25<1:19:30, 67.19s/it]

Best trial: 28. Best value: 0.136138:  30%|███       | 30/100 [32:25<1:31:11, 78.17s/it]

Best trial: 28. Best value: 0.136138:  30%|███       | 30/100 [32:42<1:31:11, 78.17s/it]

Best trial: 28. Best value: 0.136138:  31%|███       | 31/100 [32:42<1:08:48, 59.83s/it]

Best trial: 28. Best value: 0.136138:  31%|███       | 31/100 [33:34<1:08:48, 59.83s/it]

Best trial: 28. Best value: 0.136138:  32%|███▏      | 32/100 [33:34<1:05:05, 57.43s/it]

Best trial: 28. Best value: 0.136138:  32%|███▏      | 32/100 [34:36<1:05:05, 57.43s/it]

Best trial: 28. Best value: 0.136138:  33%|███▎      | 33/100 [34:36<1:05:29, 58.65s/it]

Best trial: 28. Best value: 0.136138:  33%|███▎      | 33/100 [35:23<1:05:29, 58.65s/it]

Best trial: 28. Best value: 0.136138:  34%|███▍      | 34/100 [35:23<1:00:56, 55.39s/it]

Best trial: 28. Best value: 0.136138:  34%|███▍      | 34/100 [36:21<1:00:56, 55.39s/it]

Best trial: 28. Best value: 0.136138:  35%|███▌      | 35/100 [36:21<1:00:49, 56.14s/it]

Best trial: 28. Best value: 0.136138:  35%|███▌      | 35/100 [37:11<1:00:49, 56.14s/it]

Best trial: 28. Best value: 0.136138:  36%|███▌      | 36/100 [37:11<57:46, 54.16s/it]

Best trial: 28. Best value: 0.136138:  36%|███▌      | 36/100 [38:28<57:46, 54.16s/it]

Best trial: 28. Best value: 0.136138:  37%|███▋      | 37/100 [38:28<1:04:13, 61.17s/it]

Best trial: 28. Best value: 0.136138:  37%|███▋      | 37/100 [39:37<1:04:13, 61.17s/it]

Best trial: 28. Best value: 0.136138:  38%|███▊      | 38/100 [39:37<1:05:28, 63.36s/it]

Best trial: 28. Best value: 0.136138:  38%|███▊      | 38/100 [40:03<1:05:28, 63.36s/it]

Best trial: 28. Best value: 0.136138:  39%|███▉      | 39/100 [40:03<53:00, 52.15s/it]

Best trial: 28. Best value: 0.136138:  39%|███▉      | 39/100 [40:59<53:00, 52.15s/it]

Best trial: 28. Best value: 0.136138:  40%|████      | 40/100 [40:59<53:18, 53.32s/it]

Best trial: 28. Best value: 0.136138:  40%|████      | 40/100 [42:05<53:18, 53.32s/it]

Best trial: 28. Best value: 0.136138:  41%|████      | 41/100 [42:05<56:14, 57.20s/it]

Best trial: 28. Best value: 0.136138:  41%|████      | 41/100 [43:11<56:14, 57.20s/it]

Best trial: 28. Best value: 0.136138:  42%|████▏     | 42/100 [43:11<57:52, 59.87s/it]

Best trial: 28. Best value: 0.136138:  42%|████▏     | 42/100 [44:30<57:52, 59.87s/it]

Best trial: 28. Best value: 0.136138:  43%|████▎     | 43/100 [44:30<1:02:15, 65.54s/it]

Best trial: 28. Best value: 0.136138:  43%|████▎     | 43/100 [45:33<1:02:15, 65.54s/it]

Best trial: 28. Best value: 0.136138:  44%|████▍     | 44/100 [45:33<1:00:35, 64.91s/it]

Best trial: 28. Best value: 0.136138:  44%|████▍     | 44/100 [46:40<1:00:35, 64.91s/it]

Best trial: 28. Best value: 0.136138:  45%|████▌     | 45/100 [46:40<59:49, 65.26s/it]

Best trial: 28. Best value: 0.136138:  45%|████▌     | 45/100 [47:17<59:49, 65.26s/it]

Best trial: 28. Best value: 0.136138:  46%|████▌     | 46/100 [47:17<51:07, 56.80s/it]

Best trial: 28. Best value: 0.136138:  46%|████▌     | 46/100 [48:23<51:07, 56.80s/it]

Best trial: 28. Best value: 0.136138:  47%|████▋     | 47/100 [48:23<52:46, 59.75s/it]

Best trial: 28. Best value: 0.136138:  47%|████▋     | 47/100 [49:11<52:46, 59.75s/it]

Best trial: 28. Best value: 0.136138:  48%|████▊     | 48/100 [49:11<48:32, 56.00s/it]

Best trial: 28. Best value: 0.136138:  48%|████▊     | 48/100 [50:11<48:32, 56.00s/it]

Best trial: 28. Best value: 0.136138:  49%|████▉     | 49/100 [50:11<48:47, 57.40s/it]

Best trial: 28. Best value: 0.136138:  49%|████▉     | 49/100 [50:57<48:47, 57.40s/it]

Best trial: 28. Best value: 0.136138:  50%|█████     | 50/100 [50:57<45:02, 54.06s/it]

Best trial: 28. Best value: 0.136138:  50%|█████     | 50/100 [51:16<45:02, 54.06s/it]

Best trial: 28. Best value: 0.136138:  51%|█████     | 51/100 [51:16<35:25, 43.37s/it]

Best trial: 51. Best value: 0.136155:  51%|█████     | 51/100 [52:10<35:25, 43.37s/it]

Best trial: 51. Best value: 0.136155:  52%|█████▏    | 52/100 [52:10<37:16, 46.59s/it]

Best trial: 51. Best value: 0.136155:  52%|█████▏    | 52/100 [52:37<37:16, 46.59s/it]

Best trial: 51. Best value: 0.136155:  53%|█████▎    | 53/100 [52:37<31:56, 40.79s/it]

Best trial: 51. Best value: 0.136155:  53%|█████▎    | 53/100 [53:50<31:56, 40.79s/it]

Best trial: 51. Best value: 0.136155:  54%|█████▍    | 54/100 [53:50<38:37, 50.39s/it]

Best trial: 51. Best value: 0.136155:  54%|█████▍    | 54/100 [54:24<38:37, 50.39s/it]

Best trial: 51. Best value: 0.136155:  55%|█████▌    | 55/100 [54:24<34:08, 45.53s/it]

Best trial: 51. Best value: 0.136155:  55%|█████▌    | 55/100 [55:05<34:08, 45.53s/it]

Best trial: 51. Best value: 0.136155:  56%|█████▌    | 56/100 [55:05<32:24, 44.19s/it]

Best trial: 51. Best value: 0.136155:  56%|█████▌    | 56/100 [56:00<32:24, 44.19s/it]

Best trial: 51. Best value: 0.136155:  57%|█████▋    | 57/100 [56:00<33:54, 47.31s/it]

Best trial: 51. Best value: 0.136155:  57%|█████▋    | 57/100 [57:17<33:54, 47.31s/it]

Best trial: 51. Best value: 0.136155:  58%|█████▊    | 58/100 [57:17<39:23, 56.26s/it]

Best trial: 51. Best value: 0.136155:  58%|█████▊    | 58/100 [58:56<39:23, 56.26s/it]

Best trial: 51. Best value: 0.136155:  59%|█████▉    | 59/100 [58:56<47:11, 69.06s/it]

Best trial: 51. Best value: 0.136155:  59%|█████▉    | 59/100 [1:00:33<47:11, 69.06s/it]

Best trial: 51. Best value: 0.136155:  60%|██████    | 60/100 [1:00:33<51:35, 77.40s/it]

Best trial: 51. Best value: 0.136155:  60%|██████    | 60/100 [1:01:36<51:35, 77.40s/it]

Best trial: 51. Best value: 0.136155:  61%|██████    | 61/100 [1:01:36<47:32, 73.14s/it]

Best trial: 51. Best value: 0.136155:  61%|██████    | 61/100 [1:02:30<47:32, 73.14s/it]

Best trial: 51. Best value: 0.136155:  62%|██████▏   | 62/100 [1:02:30<42:43, 67.47s/it]

Best trial: 62. Best value: 0.136155:  62%|██████▏   | 62/100 [1:03:12<42:43, 67.47s/it]

Best trial: 62. Best value: 0.136155:  63%|██████▎   | 63/100 [1:03:12<36:55, 59.88s/it]

Best trial: 62. Best value: 0.136155:  63%|██████▎   | 63/100 [1:03:50<36:55, 59.88s/it]

Best trial: 62. Best value: 0.136155:  64%|██████▍   | 64/100 [1:03:50<31:52, 53.13s/it]

Best trial: 62. Best value: 0.136155:  64%|██████▍   | 64/100 [1:04:54<31:52, 53.13s/it]

Best trial: 62. Best value: 0.136155:  65%|██████▌   | 65/100 [1:04:54<33:00, 56.59s/it]

Best trial: 62. Best value: 0.136155:  65%|██████▌   | 65/100 [1:05:41<33:00, 56.59s/it]

Best trial: 62. Best value: 0.136155:  66%|██████▌   | 66/100 [1:05:41<30:26, 53.73s/it]

Best trial: 62. Best value: 0.136155:  66%|██████▌   | 66/100 [1:06:27<30:26, 53.73s/it]

Best trial: 62. Best value: 0.136155:  67%|██████▋   | 67/100 [1:06:27<28:14, 51.36s/it]

Best trial: 62. Best value: 0.136155:  67%|██████▋   | 67/100 [1:07:03<28:14, 51.36s/it]

Best trial: 62. Best value: 0.136155:  68%|██████▊   | 68/100 [1:07:03<24:53, 46.66s/it]

Best trial: 62. Best value: 0.136155:  68%|██████▊   | 68/100 [1:07:35<24:53, 46.66s/it]

Best trial: 62. Best value: 0.136155:  69%|██████▉   | 69/100 [1:07:35<21:49, 42.25s/it]

Best trial: 62. Best value: 0.136155:  69%|██████▉   | 69/100 [1:08:15<21:49, 42.25s/it]

Best trial: 62. Best value: 0.136155:  70%|███████   | 70/100 [1:08:15<20:48, 41.61s/it]

Best trial: 62. Best value: 0.136155:  70%|███████   | 70/100 [1:09:51<20:48, 41.61s/it]

Best trial: 62. Best value: 0.136155:  71%|███████   | 71/100 [1:09:51<27:54, 57.75s/it]

Best trial: 62. Best value: 0.136155:  71%|███████   | 71/100 [1:10:57<27:54, 57.75s/it]

Best trial: 62. Best value: 0.136155:  72%|███████▏  | 72/100 [1:10:57<28:13, 60.48s/it]

Best trial: 62. Best value: 0.136155:  72%|███████▏  | 72/100 [1:11:57<28:13, 60.48s/it]

Best trial: 62. Best value: 0.136155:  73%|███████▎  | 73/100 [1:11:57<27:05, 60.20s/it]

Best trial: 62. Best value: 0.136155:  73%|███████▎  | 73/100 [1:13:02<27:05, 60.20s/it]

Best trial: 62. Best value: 0.136155:  74%|███████▍  | 74/100 [1:13:02<26:47, 61.81s/it]

Best trial: 62. Best value: 0.136155:  74%|███████▍  | 74/100 [1:13:58<26:47, 61.81s/it]

Best trial: 62. Best value: 0.136155:  75%|███████▌  | 75/100 [1:13:58<24:58, 59.93s/it]

Best trial: 62. Best value: 0.136155:  75%|███████▌  | 75/100 [1:14:46<24:58, 59.93s/it]

Best trial: 62. Best value: 0.136155:  76%|███████▌  | 76/100 [1:14:46<22:31, 56.32s/it]

Best trial: 62. Best value: 0.136155:  76%|███████▌  | 76/100 [1:16:22<22:31, 56.32s/it]

Best trial: 62. Best value: 0.136155:  77%|███████▋  | 77/100 [1:16:22<26:10, 68.30s/it]

Best trial: 62. Best value: 0.136155:  77%|███████▋  | 77/100 [1:17:17<26:10, 68.30s/it]

Best trial: 62. Best value: 0.136155:  78%|███████▊  | 78/100 [1:17:17<23:31, 64.16s/it]

Best trial: 62. Best value: 0.136155:  78%|███████▊  | 78/100 [1:17:47<23:31, 64.16s/it]

Best trial: 62. Best value: 0.136155:  79%|███████▉  | 79/100 [1:17:47<18:56, 54.13s/it]

Best trial: 62. Best value: 0.136155:  79%|███████▉  | 79/100 [1:19:17<18:56, 54.13s/it]

Best trial: 62. Best value: 0.136155:  80%|████████  | 80/100 [1:19:17<21:32, 64.64s/it]

Best trial: 62. Best value: 0.136155:  80%|████████  | 80/100 [1:20:40<21:32, 64.64s/it]

Best trial: 62. Best value: 0.136155:  81%|████████  | 81/100 [1:20:40<22:13, 70.17s/it]

Best trial: 62. Best value: 0.136155:  81%|████████  | 81/100 [1:21:58<22:13, 70.17s/it]

Best trial: 62. Best value: 0.136155:  82%|████████▏ | 82/100 [1:21:58<21:48, 72.70s/it]

Best trial: 62. Best value: 0.136155:  82%|████████▏ | 82/100 [1:23:20<21:48, 72.70s/it]

Best trial: 62. Best value: 0.136155:  83%|████████▎ | 83/100 [1:23:20<21:22, 75.42s/it]

Best trial: 62. Best value: 0.136155:  83%|████████▎ | 83/100 [1:24:16<21:22, 75.42s/it]

Best trial: 62. Best value: 0.136155:  84%|████████▍ | 84/100 [1:24:16<18:31, 69.45s/it]

Best trial: 62. Best value: 0.136155:  84%|████████▍ | 84/100 [1:25:11<18:31, 69.45s/it]

Best trial: 62. Best value: 0.136155:  85%|████████▌ | 85/100 [1:25:11<16:18, 65.26s/it]

Best trial: 62. Best value: 0.136155:  85%|████████▌ | 85/100 [1:25:53<16:18, 65.26s/it]

Best trial: 62. Best value: 0.136155:  86%|████████▌ | 86/100 [1:25:53<13:37, 58.42s/it]

Best trial: 62. Best value: 0.136155:  86%|████████▌ | 86/100 [1:26:36<13:37, 58.42s/it]

Best trial: 62. Best value: 0.136155:  87%|████████▋ | 87/100 [1:26:36<11:38, 53.76s/it]

Best trial: 62. Best value: 0.136155:  87%|████████▋ | 87/100 [1:27:32<11:38, 53.76s/it]

Best trial: 62. Best value: 0.136155:  88%|████████▊ | 88/100 [1:27:32<10:50, 54.23s/it]

Best trial: 62. Best value: 0.136155:  88%|████████▊ | 88/100 [1:28:16<10:50, 54.23s/it]

Best trial: 62. Best value: 0.136155:  89%|████████▉ | 89/100 [1:28:16<09:24, 51.36s/it]

Best trial: 62. Best value: 0.136155:  89%|████████▉ | 89/100 [1:29:00<09:24, 51.36s/it]

Best trial: 62. Best value: 0.136155:  90%|█████████ | 90/100 [1:29:00<08:09, 48.91s/it]

Best trial: 90. Best value: 0.136187:  90%|█████████ | 90/100 [1:30:16<08:09, 48.91s/it]

Best trial: 90. Best value: 0.136187:  91%|█████████ | 91/100 [1:30:16<08:35, 57.27s/it]

Best trial: 91. Best value: 0.136323:  91%|█████████ | 91/100 [1:31:34<08:35, 57.27s/it]

Best trial: 91. Best value: 0.136323:  92%|█████████▏| 92/100 [1:31:34<08:26, 63.34s/it]

Best trial: 91. Best value: 0.136323:  92%|█████████▏| 92/100 [1:33:04<08:26, 63.34s/it]

Best trial: 91. Best value: 0.136323:  93%|█████████▎| 93/100 [1:33:04<08:20, 71.54s/it]

Best trial: 91. Best value: 0.136323:  93%|█████████▎| 93/100 [1:34:28<08:20, 71.54s/it]

Best trial: 91. Best value: 0.136323:  94%|█████████▍| 94/100 [1:34:28<07:31, 75.23s/it]

Best trial: 91. Best value: 0.136323:  94%|█████████▍| 94/100 [1:35:50<07:31, 75.23s/it]

Best trial: 91. Best value: 0.136323:  95%|█████████▌| 95/100 [1:35:50<06:26, 77.25s/it]

Best trial: 91. Best value: 0.136323:  95%|█████████▌| 95/100 [1:37:19<06:26, 77.25s/it]

Best trial: 91. Best value: 0.136323:  96%|█████████▌| 96/100 [1:37:19<05:22, 80.68s/it]

Best trial: 91. Best value: 0.136323:  96%|█████████▌| 96/100 [1:39:12<05:22, 80.68s/it]

Best trial: 91. Best value: 0.136323:  97%|█████████▋| 97/100 [1:39:12<04:30, 90.30s/it]

Best trial: 97. Best value: 0.136621:  97%|█████████▋| 97/100 [1:40:41<04:30, 90.30s/it]

Best trial: 97. Best value: 0.136621:  98%|█████████▊| 98/100 [1:40:41<02:59, 89.88s/it]

Best trial: 98. Best value: 0.13665:  98%|█████████▊| 98/100 [1:42:20<02:59, 89.88s/it]

Best trial: 98. Best value: 0.13665:  99%|█████████▉| 99/100 [1:42:20<01:32, 92.67s/it]

Best trial: 98. Best value: 0.13665:  99%|█████████▉| 99/100 [1:43:51<01:32, 92.67s/it]

Best trial: 98. Best value: 0.13665: 100%|██████████| 100/100 [1:43:51<00:00, 92.22s/it]

Best trial: 98. Best value: 0.13665: 100%|██████████| 100/100 [1:43:51<00:00, 62.31s/it]

Best CV PR-AUC: 0.1366
Best params: {'n_estimators': 565, 'max_depth': 8, 'min_samples_split': 25, 'min_samples_leaf': 1, 'max_features': 0.950123145432255}

In [7]:
tuned_rf = RandomForestClassifier(
    **study_rf.best_params, class_weight="balanced_subsample",
    random_state=RANDOM_STATE, n_jobs=-1,
)
tuned_rf.fit(X_train, y_train)

tuned_models["Random Forest (tuned)"] = tuned_rf
tune_results.append(evaluate_model("Random Forest (tuned)", tuned_rf, X_test, y_test, study_rf.best_value, stage="tuned"))

Random Forest (tuned): CV=0.1366 | Test AUC=0.6096 | PR-AUC=0.1391 | opt_thr=0.4943 | Precision=0.1350 | Recall=0.7806 | F1=0.2302

2026/07/04 23:58:56 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

## 2.4 Model Comparison
Ranked by **PR-AUC** (threshold-independent, appropriate for this class imbalance).

In [8]:
all_results = pd.DataFrame(results + tune_results).sort_values("PR-AUC", ascending=False)
all_results.reset_index(drop=True)

,Model,CV PR-AUC,CV Std,Test AUC,PR-AUC,Optimal Threshold,Precision (at-risk),Recall (at-risk),F1 (at-risk)
0,XGBoost (tuned),0.1369,-,0.6097,0.1391,0.5969,0.1351,0.7976,0.2310
1,Random Forest (tuned),0.1366,-,0.6096,0.1391,0.4943,0.1350,0.7806,0.2302
2,Logistic Regression,0.1270,0.0021,0.5732,0.1273,0.4897,0.1267,0.7789,0.2180

In [9]:
# Pick overall best model by PR-AUC
best_row   = all_results.iloc[0]
best_name  = best_row['Model']
best_model = tuned_models.get(best_name, fitted_models.get(best_name))
best_threshold = best_row['Optimal Threshold']

print(f"Best model: {best_name}")
print(f"PR-AUC: {best_row['PR-AUC']}")
print(f"Test AUC: {best_row['Test AUC']}")
print(f"Optimal threshold: {best_threshold}")
print(f"Precision (at-risk): {best_row['Precision (at-risk)']}")
print(f"Recall (at-risk): {best_row['Recall (at-risk)']}")
print(f"F1 (at-risk): {best_row['F1 (at-risk)']}")

y_prob_best = best_model.predict_proba(X_test)[:, 1]
y_pred_best = (y_prob_best >= best_threshold).astype(int)
print("\nFull classification report (at optimal threshold):")
print(classification_report(y_test, y_pred_best,
                            target_names=['Returned (0)', 'At-Risk (1)']))

Best model: XGBoost (tuned)
PR-AUC: 0.1391
Test AUC: 0.6097
Optimal threshold: 0.5969
Precision (at-risk): 0.1351
Recall (at-risk): 0.7976
F1 (at-risk): 0.231

Full classification report (at optimal threshold):
              precision    recall  f1-score   support

Returned (0)       0.94      0.39      0.55     58219
 At-Risk (1)       0.14      0.80      0.23      6937

    accuracy                           0.43     65156
   macro avg       0.54      0.59      0.39     65156
weighted avg       0.86      0.43      0.52     65156

In [10]:
# Save best model + comparison table + its optimal threshold
all_results.to_csv(OUTPUT_DIR / 'model_comparison.csv', index=False)
joblib.dump(best_model, OUTPUT_DIR / 'best_model.pkl')
joblib.dump(best_name,  OUTPUT_DIR / 'best_model_name.pkl')
joblib.dump(float(best_threshold), OUTPUT_DIR / 'optimal_threshold.pkl')

# Save all individual models
for name, m in {**fitted_models, **tuned_models}.items():
    safe = name.lower().replace(' ', '_').replace('(', '').replace(')', '')
    joblib.dump(m, OUTPUT_DIR / f'model_{safe}.pkl')

# Mark the winning run in MLflow so it is easy to find in the UI
best_run = mlflow.search_runs(
    filter_string=f"tags.algorithm = '{best_name}'",
    order_by=['start_time DESC'],
    max_results=1,
)
if not best_run.empty:
    with mlflow.start_run(run_id=best_run.iloc[0]['run_id']):
        mlflow.set_tag('selected_as_best', 'true')
        mlflow.log_artifact(str(OUTPUT_DIR / 'model_comparison.csv'))

print("Saved: best_model.pkl, best_model_name.pkl, optimal_threshold.pkl, model_comparison.csv, all individual models")
print(f'Best model logged to MLflow. Run: mlflow ui --backend-store-uri file:./mlruns  (then open http://127.0.0.1:5000)')
print("Next: run 03_evaluate.ipynb")

Saved: best_model.pkl, best_model_name.pkl, optimal_threshold.pkl, model_comparison.csv, all individual models
Best model logged to MLflow. Run: mlflow ui --backend-store-uri file:./mlruns  (then open http://127.0.0.1:5000)
Next: run 03_evaluate.ipynb